(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var u3=function(a){a.ea("cardstatechange",a.Eh()&&a.wk()?1:0)},v3=function(a,b){var c=g.Na(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},lRa=function(a){var b=g.Pm(a);
a=g.Vm(a);return new g.Cm(b.x,b.y,a.width,a.height)},mRa=function(a){return Math.pow(a,3)},nRa=function(a){return 3*a*a-2*a*a*a},y3=function(a){a=g.Qa(a);
delete w3[a];g.Se(w3)&&x3&&x3.stop()},pRa=function(){x3||(x3=new g.I(function(){oRa()},20));
var a=x3;a.isActive()||a.start()},oRa=function(){var a=g.Ta();
g.De(w3,function(b){qRa(b,a)});
g.Se(w3)||pRa()},z3=function(a,b,c,d){g.$r.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.S=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.K=0;this.D=null},qRa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;rRa(a,a.progress);1==a.progress?(a.i=0,y3(a),a.onFinish(),a.Gw()):a.Ec()&&a.jC()},rRa=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.S[c]-a.u[c])*b+a.u[c]},sRa=function(a,b){g.ue.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.i},A3=function(a,b,c,d,e){z3.call(this,b,c,d,e);
this.element=a},B3=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
A3.call(this,a,b,c,d,e)},C3=function(a){g.E.call(this);
this.u=a||window;this.i=[]},D3=function(a){return a.baseUrl||null},E3=function(a,b){return g.Bp(g.nn(a,b,void 0),function(c){return!!c})},tRa=function(a,b,c){function d(X){var la,Ea,qb,ib=X.hovercardButton;
if(!ib)return null;ib=ib.subscribeButtonRenderer;if(!ib)return null;var Bb=f(ib.unsubscribedButtonText),lc=f(ib.subscribedButtonText);if(ib.subscribed){var Sa=f(ib.subscriberCountWithUnsubscribeText);var cc=f(ib.subscriberCountText)}else Sa=f(ib.subscriberCountText),cc=f(ib.subscriberCountWithSubscribeText);var Jb=null;return X.signinEndpoint&&(Jb=v3(X,"signinEndpoint","webNavigationEndpointData","url"),Jb||(Jb=null===(qb=null===(Ea=null===(la=ib.signInEndpoint)||void 0===la?void 0:la.commandMetadata)||
void 0===Ea?void 0:Ea.webCommandMetadata)||void 0===qb?void 0:qb.url),!Jb)?null:Bb&&(lc||Jb)?{subscribed:ib.subscribed,subscribeText:Bb,subscribeCount:Sa,unsubscribeText:lc,unsubscribeCount:cc,enabled:ib.enabled,signinUrl:Jb,classic:X.useClassicSubscribeButton}:null}
function e(X){if(X){var la=[],Ea=X.videoId;Ea&&la.push("v="+Ea);(Ea=X.playlistId)&&la.push("list="+Ea);(X=X.startTimeSeconds)&&la.push("t="+X);return"/watch?"+la.join("&")}}
function f(X){if(!X)return null;var la=X.simpleText;return la?la:X.runs?g.nn(X.runs,function(Ea){return Ea.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,r=null,t=null,u=null,v=!1,y=null,z=null,D=null,F=null,G=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,r=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(v=v3(l,"browseEndpoint","browseId"))u=v,m="/channel/"+u;n=!1;p="new";(v=!!b.isSubscribe)?y=d(b):z=f(b.subscribersText)}else"WEBSITE"===
h?((D=v3(l,"urlEndpoint","url"))&&(m=D),n=!0,p="new",D=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(F=f(b.productPrice)),b.additionalFeesText&&(G=f(b.additionalFeesText)),(n=v3(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=v3(b,"title","accessibility","accessibilityData","label");var J=b.endpoint?b.endpoint.clickTrackingParams:null,U="";if(b.metadata){var K=f(b.metadata);K&&(U=K)}return{id:"element-"+c,type:h,title:f(b.title),metadata:U,callToAction:f(b.callToAction),fK:b.image,
iconUrl:D,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,playlistLength:t,channelId:u,subscribeButton:y,subscribersText:z,isSubscribe:v,targetUrl:m||null,XS:n,sessionData:J?{itct:J}:null,GX:p,Lu:a?a:null,aT:b.isPlaceholder,impressionUrls:E3(b.impressionUrls||[],D3),PS:E3(b.hovercardShowUrls||[],D3),clickUrls:E3(l.loggingUrls||[],D3),visualElement:g.Vx(b.trackingParams),
productPrice:F,additionalFeesText:G}},F3=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:E3(a.impressionUrls||[],D3),elements:E3(a.elements||[],function(d,e){return tRa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Vx(a.trackingParams));return c},G3=function(a){g.GM.call(this,a);
this.B=this.endscreen=null;this.i={};this.D={};this.C=this.u=null;this.K=[];this.X=!0;this.I=0;a=a.V();this.S=g.sE(a)||g.wE(a);this.events=new g.LC(this);g.H(this,this.events);this.events.T(this.player,g.Zy("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.$y("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.xb);this.events.T(window,"focus",this.KW);this.load();var b=g.bh("STYLE");(g.Og("HEAD")[0]||document.body).appendChild(b);g.te(this,function(){g.fh(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},uRa=function(a){return a.player.getVideoData().D?"current":a.S?"new":"current"},H3=function(a){return"creator-endscreen-editor"===a.player.V().playerStyle},vRa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=F3(f,uRa(a))));I3(a,f)},
urlParams:{v:c},withCredentials:!0};a.S&&(c.urlParams.ptype="embedded");var d=b.hq;d&&(c.postParams={ad_tracking:d});if(b=g.hsa(b))if(b=g.Wf(b),b=g.Qf(b))a.B=g.lu(b,c)},I3=function(a,b,c){c=void 0===c?!0:c;
a.player.Ye("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.q(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.D={};0<a.K.length&&(a.K.forEach(function(l){l.dispose()}),a.K.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&wRa(a);c=[];d=new g.Xy(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().isMobile||(a.u=new g.W({G:"div",L:"ytp-ce-shadow"}),g.tM(a.player,a.u.element,4),a.C=new g.$K(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=xRa(a,e);if(f){a.i[e.id]=f;a.D[e.id]=e;g.tM(a.player,f.element,4);var h=new g.Xy(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);yRa(a,
f,e)}else g.gy(new g.ew("buildEndscreenElement null",e))}a.player.Dd(c);a.xb()}},wRa=function(a){var b=g.Yx(),c=g.Zx();
c&&b&&a.endscreen.visualElement&&g.ky(void 0,c,b,[a.endscreen.visualElement])},xRa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.N("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ha:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":b.Lu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:J3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:K3(a,b.targetUrl),tabindex:"-1"},U:[{G:"div",Ha:["ytp-ce-video-title"].concat(g.ma(c)),W:{dir:g.es(b.title||
"")},va:b.title},{G:"div",L:"ytp-ce-video-duration",va:b.videoDuration||void 0}]}]};c=new g.W(a);break;case "PLAYLIST":c=a.player.N("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ha:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":b.Lu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:J3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:K3(a,
b.targetUrl),tabindex:"-1"},U:[{G:"div",Ha:["ytp-ce-playlist-title"].concat(g.ma(c)),W:{dir:g.es(b.title||"")},va:b.title},{G:"div",L:"ytp-ce-playlist-count",U:[{G:"div",L:"ytp-ce-playlist-icon"},{G:"div",L:"ytp-ce-playlist-count-text",va:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={G:"div",Ha:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":b.Lu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},
{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"a",Ha:["ytp-ce-channel-title","ytp-ce-link"],W:{href:K3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.es(b.title||"")},va:b.title},b.subscribeButton?{G:"div",L:"ytp-ce-subscribe-container",U:[{G:"div",L:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{G:"div",L:"ytp-ce-channel-subscribers-text",va:b.subscribersText}:"",b.metadata?{G:"div",Ha:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],va:b.metadata}:""]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:J3(b)}]};c=new g.W(c);var d=g.Pg(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.L(d,"ytp-ce-subscribe-button");if(a.player.V().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.JN(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.K.push(e)}break;case "WEBSITE":a={G:"div",Ha:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":b.Lu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},
{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"div",L:"ytp-ce-website-title",W:{dir:g.es(b.title||"")},va:b.title},{G:"div",L:"ytp-ce-website-metadata",va:b.metadata},{G:"a",Ha:["ytp-ce-website-goto","ytp-ce-link"],W:{href:K3(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:J3(b)},{G:"div",
L:"ytp-ce-expanding-icon",W:zRa(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",L:"ytp-ce-merchandise-price-container",U:[{G:"div",L:"ytp-ce-merchandise-price",va:b.productPrice}]},b.additionalFeesText&&c.U.push({G:"div",L:"ytp-ce-merchandise-additional-fees",va:b.additionalFeesText})),a={G:"div",Ha:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":b.Lu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",
U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"div",L:"ytp-ce-merchandise-title",W:{dir:g.es(b.title||"")},va:b.title},c,{G:"div",L:"ytp-ce-merchandise-metadata",va:b.metadata},{G:"a",Ha:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:K3(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},
{G:"div",L:"ytp-ce-expanding-image",W:J3(b)},{G:"div",L:"ytp-ce-merchandise-invideo-cta-container",U:[{G:"div",L:"ytp-ce-merchandise-invideo-cta",va:b.callToAction||void 0}]}]},c=new g.W(a)}b.aT&&g.L(c.element,"ytp-ce-placeholder");return c},J3=function(a){if(a.fK)var b=a.fK.thumbnails;
return zRa(b?b[b.length-1].url:null)},zRa=function(a){return a?{style:"background-image: url("+a+")"}:{}},yRa=function(a,b,c){function d(m){m&&(b.Ra("blur",function(){"none"!=m.style.display&&a.X&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.L(b.element,"ytp-ce-force-expand"),L3(a,c.id,!0)):(g.Qr(b.element,"ytp-ce-force-expand"),g.Qr(b.element,"ytp-ce-element-hover"),L3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ra("mouseenter",function(){M3(a,b,c)});
b.Ra("mouseleave",function(){N3(a,b,c)});
a.player.V().isMobile||b.Ra("click",function(){g.L(b.element,"ytp-ce-element-hover")});
b.Ra("click",function(m){ARa(a,c,m)});
b.Ra("keypress",function(m){ARa(a,c,m)});
b.Ra("focus",function(){M3(a,b,c)});
b.Ra("blur",function(){N3(a,b,c)});
b.Ra("touchstart",function(){M3(a,b,c)});
var l=g.Rg("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.Qr(b.element,"ytp-ce-element-hover");g.Qr(b.element,"ytp-ce-force-expand")});
b.Ra("keydown",function(m){a.X=9===m.keyCode&&!m.shiftKey});
d(g.Rg("ytp-sb-subscribe",b.element));d(g.Rg("ytp-sb-unsubscribe",b.element));b.Ra("focus",f);b.Ra("blur",h)},ARa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Or(d,"ytp-ce-element");){g.Or(d,"subscribe-label")&&O3(a,b);
if(g.Or(d,"ytp-ce-channel-subscribe"))return;d=g.gh(d)}if(!d||g.Or(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])N3(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.GX)O3(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Wf(K3(a,b.targetUrl)),c=g.Qf(c),g.zL(c,void 0,b.sessionData);else{var e=a.player.getVideoData().D,f=function(){var h=K3(a,b.targetUrl),l=b.sessionData,m=g.Ht(h);e&&m&&(m.v||m.list)?a.player.Tj(m.v,l,m.list,!1):
g.yL(h,l)};
O3(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},K3=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.VE(a)+b}else return"";return b},M3=function(a,b,c){g.Or(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.L(b.element,"ytp-ce-element-hover"):a.player.V().isMobile?(new g.I(function(){g.L(b.element,"ytp-ce-element-hover")},200)).start():g.L(b.element,"ytp-ce-element-hover"),P3(a,c.PS),L3(a,c.id,!0))},N3=function(a,b,c){g.Qr(b.element,"ytp-ce-element-hover");
g.Qr(b.element,"ytp-ce-force-expand");L3(a,c.id,!1)},L3=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.q(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.M(a.i[e].element,"ytp-ce-element-shadow-show",c)},P3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||H3(a))c&&c();else{b=BRa(a,b);var e=0,f=!1,h=new g.I(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.ov(b[a],d)}},O3=function(a,b,c){P3(a,b.clickUrls,c);
(a=g.Zx())&&b.XS&&g.qy(a,b.visualElement)},BRa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(CRa(b[d],c));return a},CRa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},DRa=function(a){return"string"===typeof a?a:""},Q3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},ERa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},R3=function(a){return a.value?a.value:null},S3=function(a){if(!a)return null;
var b=g.Wf(DRa(a.value));b=g.Qf(b);if(!b)return null;var c=Q3(a.target,FRa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new ERa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},GRa=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},JRa=function(a){if(!a)return null;
var b=Q3(a.type,HRa),c=Q3(a.trigger,IRa);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=S3(a?a:null);return b?new GRa(b,c,a):null},KRa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},MRa=function(a){return(a=LRa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},LRa=function(a,b){return g.Tb(a.action,b,void 0)},NRa=function(a,b){this.context=a;
this.i=b},U3=function(a){return a.customMessage?T3("div","iv-card-message",a.customMessage):""},V3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",L:"iv-card-image",W:{style:a},U:c}},W3=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.q(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(T3("li","",c.value));return{G:"ul",L:"iv-card-meta-info",U:b}},T3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.es(c);return{G:a,W:b,va:c}},ORa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.uy&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.uy+");");c.dir=g.es(a.customMessage);var d=[{G:"span",va:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",L:"iv-card-link-icon"}));return{G:"div",Ha:b,W:c,U:d}},X3=function(a,b,c,d){if(d){b=g.q(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},PRa=function(a,b){this.merchant=a;
this.price=b},QRa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},RRa=function(a,b){return b?b:QRa(a)?"current":"new"},Y3=function(a,b){g.E.call(this);
var c=this;this.element=a;this.context=b;this.bb=!1;this.Sa=new Map;this.Va=new Map;this.context.J.addEventListener(g.Zy("annotations_module"),function(d){(d=c.Sa.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.$y("annotations_module"),function(d){(d=c.Va.get(d))&&d.apply(c)})},Z3=function(a,b,c,d,e,f,h){a.context.i.Ra(b,"click",function(l){a.kC(c,d,e,f||[],h||0,l)});
a.context.i.Ra(b,"touchstart",function(){a.bb=!1});
a.context.i.Ra(b,"touchmove",function(){a.bb=!0})},SRa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},$3=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
lO:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
mB:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},c4=function(a,b,c){Y3.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Ka=this.rb=this.B=this.isInitialized=!1;this.xa=null;this.cards=[];this.kb=this.S=this.Ja=this.D=this.La=this.i=null;this.Z=[];this.K=this.De=this.Ba=null;this.I=0;this.Aa=new g.I(g.Ka,c.Y.Wd?4E3:3E3);g.H(this,this.Aa);this.Za=new g.I(g.Ka);g.H(this,this.Za);this.oa=new NRa(c,function(e,f,h,l,m,n){Z3(d,e,f,h,l,m,n)});
this.X=new g.W({G:"div",L:"iv-drawer",W:{id:"iv-drawer"},U:[{G:"div",L:"iv-drawer-header",W:{"aria-role":"heading"},U:[{G:"span",L:"iv-drawer-header-text"},{G:"button",Ha:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Hide cards",tabindex:"0"}}]},{G:"div",L:"iv-drawer-content"}]});g.H(this,this.X);this.C=this.X.element;this.Wa=new g.$K(this.X,330);g.H(this,this.Wa);this.jb=g.Rg("iv-drawer-header-text",this.C);this.u=g.Rg("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.rb&&a4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.rb=d.B)&&b4(d)})},TRa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){a4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){b4(a)});
var c=b.headerText;g.ih(a.jb,c);a.S&&a.S.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ba=g.Vx(b.trackingParams);a.K=g.Vx(b.closeTrackingParams);a.De=g.Vx(b.iconTrackingParams)},URa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.dz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:d4(a,c,b,d),sponsored:!1,tracking:$3(d,e,d.command),Kl:d.trackingParams?g.Vx(d.trackingParams):null,Wi:e.trackingParams?
g.Vx(e.trackingParams):null,De:f&&f.trackingParams?g.Vx(f.trackingParams):null,imageUrl:e4(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.dz(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,uy:null,title:d.title?g.dz(d.title):"",customMessage:d.callToAction?g.dz(d.callToAction):"",url:d.command.urlEndpoint.url?S3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};f4(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.dz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:d4(a,c,b,d),sponsored:!1,tracking:$3(d,e,d.endpoint),Kl:d.trackingParams?g.Vx(d.trackingParams):null,Wi:e.trackingParams?g.Vx(e.trackingParams):null,De:f&&f.trackingParams?
g.Vx(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.dz(d.customText):null,profileImageUrl:e4(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.dz(d.channelName):"",metaInfo:[d.subscriberCountText?g.dz(d.subscriberCountText):""],url:S3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};
f4(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.dz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:d4(a,c,b,d),sponsored:!1,tracking:$3(d,e,d.action),Kl:d.trackingParams?g.Vx(d.trackingParams):
null,Wi:e.trackingParams?g.Vx(e.trackingParams):null,De:f&&f.trackingParams?g.Vx(f.trackingParams):null,Bx:e4(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.dz(d.customMessage):null,playlistVideoCount:g.dz(d.playlistVideoCount),title:d.playlistTitle?g.dz(d.playlistTitle):"",metaInfo:[d.channelName?g.dz(d.channelName):"",d.videoCountText?g.dz(d.videoCountText):""],url:S3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:SRa(d.action)})};f4(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.dz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:d4(a,c,b,d),sponsored:!1,tracking:$3(d,e,d.action),Kl:d.trackingParams?g.Vx(d.trackingParams):null,Wi:e.trackingParams?g.Vx(e.trackingParams):null,De:f&&f.trackingParams?g.Vx(f.trackingParams):
null,Bx:e4(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.dz(d.lengthString):null,customMessage:d.customMessage?g.dz(d.customMessage):null,title:d.videoTitle?g.dz(d.videoTitle):"",metaInfo:[d.channelName?g.dz(d.channelName):"",d.viewCountText?g.dz(d.viewCountText):""],isLiveNow:!!d.badge,url:S3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:SRa(d.action)})};f4(a,b)}a.I++},e4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===
a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},d4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},WRa=function(a,b){if(b=VRa(a,b))b===a.i&&(a.i=null),a.J.removeCueRange(b.card.id),g.fh(b.iD),g.$b(a.cards,b),a.wy(),g4(a)},a4=function(a,b,c){if(!a.B){a.Wa.show();
a.La=new g.I(function(){g.L(a.context.J.getRootNode(),g.eT.IV_DRAWER_OPEN)},0);
a.La.start();a.xa=g.Zu(a.u,"mousewheel",function(h){a.Aa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.Zx();d&&a.Ba&&a.K&&g.oy(d,[a.Ba,a.K]);b={TRIGGER_TYPE:b};for(var e=g.q(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.PL||(f.PL=!0,XRa(a.context.logger,f.card.tracking.impression,b)),d&&g.oy(d,[f.card.Kl]);u3(a.J);c&&(a.D=new g.I(function(){a.Ja=a.S;a.kb.focus()},330),a.D.start())}},b4=function(a){a.B&&(a.Wa.hide(),g.$u(a.xa),a.xa=null,g.Qr(a.context.J.getRootNode(),g.eT.IV_DRAWER_OPEN),a.B=!1,u3(a.J),a.D&&a.D.stop(),a.D=new g.I(function(){a.Ja&&(a.Ja.focus(),a.Ja=null)},330),a.D.start())},
ZRa=function(a){g.Pr(a.element,[g.eT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.tM(a.J,a.C,5);YRa(a);a.S=g.Rg("ytp-cards-button",a.J.getRootNode());a.kb=g.Rg("iv-drawer-close-button",a.C);a.isInitialized=!0},YRa=function(a){var b=g.Rg("iv-drawer-close-button",a.C);
a.context.i.Ra(b,"click",a.BR,a);a.context.i.Ra(a.u,"touchend",function(){a.Aa.start()});
a.context.i.Ra(a.u,"scroll",a.NR,a);a.context.u.subscribe("onHideControls",function(){a.Ka=!0});
a.context.u.subscribe("onShowControls",function(){a.Ka=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Ka=g.Or(a.J.getRootNode(),"ytp-autohide")});
a.Z.push(g.wv("iv-button-shown",a.fT,a));a.Z.push(g.wv("iv-button-hidden",a.eT,a));a.Z.push(g.wv("iv-teaser-shown",a.kQ,a));a.Z.push(g.wv("iv-teaser-hidden",a.gT,a));a.Z.push(g.wv("iv-teaser-clicked",a.jQ,a))},f4=function(a,b){a.isInitialized||ZRa(a);
WRa(a,b.id);var c=$Ra(a,b);if(c){var d={card:b,iD:c.element,PL:!1},e=aSa(a,d);g.ic(a.cards,e,0,d);c.Ea(a.u,e);a.wy();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.i=d,g4(a),bSa(a,d),a4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&cSa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){cSa(a,d)}),g4(a))}},$Ra=function(a,b){switch(b.type){case "simple":a=a.oa;
var c=b.displayDomain?{G:"div",L:"iv-card-image-text",va:b.displayDomain}:void 0;var d=ORa(b);c={G:"div",Ha:["iv-card"],U:[{G:"a",L:"iv-click-target",W:{href:b.url?R3(b.url)||"":""},U:[V3(b.imageUrl,c),{G:"div",L:"iv-card-content",U:[T3("h2",void 0,b.title),d]}]}]};c=new g.W(c);X3(a,g.Qg("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.oa,c={G:"div",Ha:["iv-card","iv-card-channel"],U:[{G:"a",Ha:["iv-click-target"],W:{href:R3(b.url)||"","data-ytid":b.channelId},U:[V3(b.profileImageUrl),
{G:"div",L:"iv-card-content",U:[U3(b),{G:"h2",L:"iv-card-primary-link",va:b.title},W3(b)]}]}]},c=new g.W(c),X3(a,g.Qg("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.oa,c={G:"div",Ha:["iv-card","iv-card-playlist"],U:[{G:"a",L:"iv-click-target",W:{href:R3(b.url)||""},U:[V3(b.Bx,{G:"div",L:"iv-card-image-overlay",U:[{G:"span",L:"iv-card-playlist-video-count",va:b.playlistVideoCount}]}),{G:"div",L:"iv-card-content",U:[U3(b),T3("h2","iv-card-primary-link",b.title),W3(b)]}]}]},c=new g.W(c),
X3(a,g.Qg("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.oa;var e=!g.Xb(b.offers);c=["iv-card"];d="";var f=ORa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({G:"div",L:"iv-card-offer-price",va:f.price}),f.merchant&&e.push({G:"div",L:"iv-card-offer-merchant",va:f.merchant}),f={G:"div",U:e});e=b.url?R3(b.url)||"":"";c={G:"div",Ha:c,W:{tabindex:"0"},U:[{G:"a",Ha:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{G:"div",L:"iv-card-content",U:[b.sponsored?{G:"div",L:"iv-card-sponsored",U:["Sponsored",{G:"div",L:"iv-ad-info-container",U:[{G:"div",L:"iv-ad-info",va:"{{adInfo}}"},{G:"div",L:"iv-ad-info-icon-container",U:[{G:"div",L:"iv-ad-info-icon"},{G:"div",L:"iv-ad-info-callout"}]}]}]}:"",{G:"a",L:"iv-click-target",W:{href:e},U:[T3("h2",d,b.title),f]}]}]};c=new g.W(c);d=g.bh("span");g.ih(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.md(d,"adInfo");X3(a,g.Qg("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.oa,d=b.videoDuration?{G:"span",L:"iv-card-video-duration",va:b.videoDuration}:void 0,f=b.isLiveNow?{G:"span",Ha:["yt-badge","yt-badge-live"],va:"LIVE NOW"}:null,e={G:"div",Ha:["iv-card","iv-card-video"],U:[{G:"a",L:"iv-click-target",W:{href:(null===(c=b.url)||void 0===c?void 0:R3(c))||""},U:[V3(b.Bx,d),{G:"div",L:"iv-card-content",U:[U3(b),T3("h2","iv-card-primary-link",b.title),W3(b),f]}]}]},c=new g.W(e),
X3(a,g.Qg("iv-click-target",c.element),b,b.url),c;default:return null}},aSa=function(a,b){if(0===a.cards.length)return 0;
a=g.Ub(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},dSa=function(a){return a.i?"productListing"===a.i.card.type:g.on(a.cards,function(b){return"productListing"===b.card.type})},g4=function(a){g.M(a.J.getRootNode(),"ytp-cards-shopping-active",dSa(a))},cSa=function(a,b){if(!g.Or(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.Zx(),d=a.i?a.i.card.De:a.De;
c&&d&&g.py(c,[d]);a.i=b;g4(a)}if(c="none"!=a.element.style.display)a.context.J.V().N("html5_enable_single_video_vod_ivar_on_pacf")||2!==a.context.J.getPresentingPlayerType()?(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=1===c||3===c||d):c=1===a.context.J.getAdState();c&&b.card.teaserDurationMs&&a.J.Et(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Za.isActive()||((!a.B||!a.Aa.isActive()&&a.Ka)&&bSa(a,b),a.Za.start(910+b.card.teaserDurationMs))}},
bSa=function(a,b){a.X.yb?(b=new z3([0,
a.u.scrollTop],[0,b.iD.offsetTop],600,nRa),a.context.B.Ra(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Ra(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.qK(a.X,!0),a.u.scrollTop=b.iD.offsetTop,g.qK(a.X,!1))},h4=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},VRa=function(a,b){return g.Tb(a.cards,function(c){return c.card.id===b})},i4=function(a,b,c){Y3.call(this,a,b);
this.annotation=c;this.isActive=!1},eSa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},j4=function(a,b,c){i4.call(this,a,b,c);
this.u=null;this.K=!1;this.B=null;this.C=!1;this.i=this.I=this.D=null},fSa=function(a,b){var c=void 0===c?0:c;
var d=lRa(b).width;g.Nm(b,d);c=new B3(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,mRa);g.H(a,c);a.context.B.Ra(c,"begin",function(){g.$m(b,!0)});
c.play()},iSa=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Ha:["iv-branding-context-name"],va:b.channel_name}),d=a.createElement({G:"div",Ha:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.JN(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.J),a.i.Ea(d));var f=a.createElement({G:"div",Ha:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",Ha:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.$m(h,!1);var l=a.createElement({G:"div",Ha:["branding-context-container-outer"]});l.appendChild(h);g.Gm(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.I(function(){gSa(a,h,l)},500);
g.H(a,a.B);a.context.i.Ra(a.element,"mouseover",function(){hSa(a,h,l,f,b.image_height)});
a.context.i.Ra(a.element,"mouseout",function(){a.B.start()})}},hSa=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Vm(b);a.i||(b.style.width=g.Mm(f.width,!0),c.style.width=g.Mm(f.width,!0));g.Gm(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Gm(d,"right","1px");a.C=!0;g.$m(b,!0);a.D=new g.I(function(){g.L(this.element,"iv-branding-active")},0,a);
a.D.start()}},gSa=function(a,b,c){g.Qr(a.element,"iv-branding-active");
a.I=new g.I(function(){g.$m(b,!1);a.i||(c.style.width=g.Mm(0,!0))},250);
a.I.start();a.C=!1},jSa=function(a,b,c,d,e,f,h){this.i=a;
this.B=b;this.Y=c;this.videoData=d;this.logger=e;this.J=f;this.u=h},k4=function(a,b,c){i4.call(this,a,b,c);
var d=this;this.S=this.isCollapsed=this.X=!1;this.I=5E3;this.u=this.B=this.i=this.C=null;this.K=this.createElement({G:"div",Ha:["iv-promo-contents"]});this.D=new g.I(function(){d.i.setAttribute("aria-hidden","true");g.$m(d.B,!1);g.$m(d.u,!0)},700,this);
g.H(this,this.D)},kSa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=MRa(a.annotation),f=b.image_url;if(f){var h=a.createElement({G:"div",Ha:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",W:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({G:"span",L:"iv-promo-video-duration",va:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",L:"iv-promo-playlist-length",va:b.playlist_length.toString()}),h.appendChild(f));e&&Z3(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",L:"iv-promo-txt"}),g.og(f,R3(e)),a.i=f):a.i=a.createElement({G:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",U:[{G:"strong",
va:b.text_line_1}]});var m=a.createElement({G:"p",U:[{G:"span",L:"iv-promo-link",va:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Ha:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Ha:["iv-button","iv-promo-button"],U:[{G:"span",L:"iv-button-content",va:f}]});var p=a.createElement({G:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&Z3(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.L(a.i,
"iv-click-target");e&&Z3(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",U:[{G:"span",va:b.text_line_1}]}),m=a.createElement({G:"p",U:[{G:"strong",va:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Ha:["yt-badge","iv-promo-badge-live"],va:"LIVE NOW"})),g.L(a.i,"iv-click-target"),e&&Z3(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.K.appendChild(a.i);p&&
a.K.appendChild(p);c=a.createElement({G:"div",L:"iv-promo-actions"});a.u=a.createElement({G:"button",Ha:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.i.Ra(a.u,"click",function(r){l4(a,5E3,r)});
c.appendChild(a.u);g.$m(a.u,!1);a.context.i.Ra(a.element,"mouseover",a.uS,a);a.context.i.Ra(a.element,"mouseout",a.tS,a);a.context.i.Ra(a.element,"touchend",function(r){l4(a,5E3,r)});
a.B=a.createElement({G:"button",Ha:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.i.Ra(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.pS:a.oS,a);c.appendChild(a.B);g.Pr(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.K);a.element.appendChild(c)},l4=function(a,b,c){c.stopPropagation();
lSa(a);mSa(a,b);a.i.focus()},nSa=function(a){a.isCollapsed||a.S||a.C||(g.L(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},lSa=function(a){a.D.stop();
a.isCollapsed&&(g.Rr(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.$m(a.u,!1),g.$m(a.B,!0))},mSa=function(a,b){a.C||(a.C=g.Yh(function(){m4(this);
nSa(this)},b,a))},m4=function(a){a.C&&(g.B.clearTimeout(a.C),a.C=null)},oSa=function(a){this.J=a},XRa=function(a,b,c){b&&(c?n4(a,b.map(function(d){return g.yr(d,c)})):n4(a,b))},n4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.q(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.ov(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},o4=function(a){g.GM.call(this,a);
var b=this;this.S=!1;this.loadNumber=0;this.I={};this.logger=new oSa(this.player);this.C=new g.LC(this);this.D=this.jl=null;this.events=new g.LC(this);this.K=this.i=null;this.X=[];g.H(this,this.C);this.C.T(this.player,"onVideoAreaChange",function(){b.ea("onVideoAreaChange")});
this.C.T(this.player,"onHideControls",function(){b.ea("onHideControls")});
this.C.T(this.player,"onShowControls",function(){b.ea("onShowControls")});
this.C.T(this.player,"resize",function(d){b.ea("resize",d)});
this.C.T(this.player,"presentingplayerstatechange",function(d){b.ea("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.lQ,this);this.subscribe("resize",this.pA,this);this.player.V().S.subscribe("vast_info_card_add",this.eN,this);g.H(this,this.events);this.Z=this.createElement({G:"div",L:"video-custom-annotations"});this.u=new g.W({G:"div",Ha:["ytp-player-content","ytp-iv-player-content"]});g.H(this,this.u);g.tM(this.player,this.u.element,4);this.u.hide();this.B=new g.W({G:"div",Ha:["ytp-iv-video-content"]});g.H(this,this.B);a=this.createElement({G:"div",L:"video-annotations"});
a.appendChild(this.Z);this.B.element.appendChild(a);this.Jq()&&this.load();var c=this.createElement({G:"style"});(g.Og("HEAD")[0]||document.body).appendChild(c);g.te(this,function(){g.fh(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},pSa=function(a){a=a.createElement({G:"div",
Ha:["annotation","annotation-type-custom"]});g.$m(a,!1);return a},qSa=function(a,b){b=!b.isCued()&&!g.T(b,1024);
g.qK(a.u,b);g.qK(a.B,b)},rSa=function(a,b,c){a.S=!0;
a.D=g.lu(b,c)},sSa=function(a,b){for(var c={},d=g.q(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Oa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(sSa(a,e))}return c},vSa=function(a){var b=a.player.getVideoData();
if(b.Va){var c=a.player.V().S.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Pt(h)&&h.responseXML?h.responseXML:null)&&p4(a,h)}};
g.Cu()&&(d.onFinish=tSa(a,d.onFinish));d.postParams={ic_only:"1"};uSa(d,c);a.S=!0;g.lu(b.Va,d)}}},uSa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.Uu&&(a.postParams.ic_coll=b.Uu);b.Cy&&(a.postParams.ic_xml=b.Cy);b.Ex&&(a.postParams.ic_track=b.Ex)},wSa=function(a){var b=new g.W({G:"div"});
g.$m(b.element,!1);var c=new c4(a.player,b.element,q4(a));g.H(c,b);b.Ea(a.u.element);c.kx();return c},q4=function(a){if(!a.K){var b=new C3(a);
g.H(a,b);var c=new g.ol(a);g.H(a,c);a.K=new jSa(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.Wd)}return a.K},p4=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Zx();if(e){var f=g.Yx();f&&g.ky(void 0,e,f,[g.Vx(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=sSa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=Q3(f.type,xSa),p=Q3(f.style,ySa),r=DRa(f.data),t=0!==r.length?JSON.parse(r):{};var u=f.action;f=JRa;if(null==u)var v=null;else if(g.Na(u)){l=[];for(var y=g.q(u),z=y.next();!z.done;z=y.next()){var D=f(z.value);
D&&l.push(D)}v=l}else{var F=f(u);v=F?[F]:[]}e=m&&n?new KRa(m,n,p,v,t):null}else e=null}catch(la){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var G=pSa(f),J=null;switch(l.type){case "branding":if(f.player.V().wb)break;f.u.element.appendChild(G);J=new j4(G,q4(f),l);break;case "promotion":g.tM(f.player,G,4),J=new k4(G,q4(f),l)}J&&J.kx();if(f=J)g.H(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.i||(a.i=wSa(a),g.H(a,a.i));if("card"===e.type){c=a.i;var U=e&&e.data&&e.data.card_type;
f=e.data;if(U)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,lO:l.teaser_impression,mB:l.teaser_click},G=f.tracking_params||{},J=null,U){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Kl:G.card?g.Vx(G.card):null,Wi:G.teaser?g.Vx(G.teaser):null,De:G.icon?g.Vx(G.icon):null,
channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:S3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};f4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Kl:G.card?g.Vx(G.card):
null,Wi:G.teaser?g.Vx(G.teaser):null,De:G.icon?g.Vx(G.icon):null,Bx:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:S3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};f4(c,e);break;case "productListing":f.signin_url&&(J=S3({target:"current",value:f.signin_url}));U=[];for(var K=f.offers||[],X=0;X<K.length;X++)U.push(new PRa(g.Dg(K[X].merchant),g.Dg(K[X].price)));e={id:e.id,
timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Kl:G.card?g.Vx(G.card):null,Wi:G.teaser?g.Vx(G.teaser):null,De:G.icon?g.Vx(G.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,uy:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:
null,url:S3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),Eda:J,Dda:f.signin_title?f.signin_title:void 0,Cda:f.signin_message?f.signin_message:void 0,offers:U};f4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Kl:G.card?g.Vx(G.card):null,Wi:G.teaser?g.Vx(G.teaser):
null,De:G.icon?g.Vx(G.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,uy:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:S3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};f4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||
!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Kl:G.card?g.Vx(G.card):null,Wi:G.teaser?g.Vx(G.teaser):null,De:G.icon?g.Vx(G.icon):null,Bx:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:S3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},f4(c,e)}}else TRa(a.i,e);c=!0}}c&&(u3(a.player),a.pA())},zSa=function(a,b){var c=!1;
a.i||(a.i=wSa(a),g.H(a,a.i));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(URa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.dz(b.headerText):"",g.ih(c.jb,d),c.S&&c.S.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ba=b.trackingParams?g.Vx(b.trackingParams):null,c.K=b.closeButton.infoCardIconRenderer.trackingParams?g.Vx(b.closeButton.infoCardIconRenderer.trackingParams):null,c.De=b.icon.infoCardIconRenderer.trackingParams?
g.Vx(b.icon.infoCardIconRenderer.trackingParams):null,u3(a.player),a.pA())},ASa=function(a,b,c,d,e){if(!a.player.V().wb){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new GRa("openUrl","click",new ERa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.dz(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.dz(b.subscriberCountText))):(b.subscriberCountText&&(e=g.dz(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.dz(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.dz(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.dz(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new KRa(c,"branding","branding",f,d);l=pSa(a);a.u.element.appendChild(l);f=new j4(l,q4(a),f);f.kx();g.H(f,f);a.I[c]=f}},tSa=function(a,b){return function(){var c=g.Ba.apply(0,arguments);
a.isDisposed()||a.X.push(g.mv.Pf(function(){b.apply(null,g.ma(c))}))}},BSa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.mM.prototype.Et=g.ca(17,function(a,b){var c=g.VM(this.tb());c&&c.Et(a,b)});
var w3={},x3=null;g.Ua(z3,g.$r);g.k=z3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.i)this.progress=0,this.coords=this.u;else if(this.Ec())return!1;y3(this);this.startTime=a=g.Ta();-1==this.i&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.mA();this.ri("play");-1==this.i&&this.ri("resume");this.i=1;var b=g.Qa(this);b in w3||(w3[b]=this);pRa();qRa(this,a);return!0};
g.k.stop=function(a){y3(this);this.i=0;a&&(this.progress=1);rRa(this,this.progress);this.ri("stop");this.Gw()};
g.k.pause=function(){this.Ec()&&(y3(this),this.i=-1,this.ri("pause"))};
g.k.ya=function(){0==this.i||this.stop(!1);this.ri("destroy");z3.je.ya.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.jC=function(){this.ri("animate")};
g.k.ri=function(a){this.dispatchEvent(new sRa(a,this))};
g.Ua(sRa,g.ue);g.Ua(A3,z3);A3.prototype.C=g.Ka;A3.prototype.jC=function(){this.C();A3.je.jC.call(this)};
A3.prototype.Gw=function(){this.C();A3.je.Gw.call(this)};
A3.prototype.mA=function(){this.C();A3.je.mA.call(this)};
g.Ua(B3,A3);B3.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(C3,g.E);C3.prototype.Ra=function(a,b,c,d){c=(0,g.C)(c,d||this.u);a=g.Zu(a,b,c);this.i.push(a);return a};
C3.prototype.Uz=function(a,b,c,d){c=(0,g.C)(c,d||this.u);a=g.Pia(a,b,c);this.i.push(a);return a};
C3.prototype.qc=function(a){g.$u(a);g.$b(this.i,a)};
C3.prototype.ya=function(){g.$u(this.i);this.i.length=0;g.E.prototype.ya.call(this)};g.w(G3,g.GM);g.k=G3.prototype;g.k.load=function(){g.GM.prototype.load.call(this);if(!H3(this)){var a=g.isa(this.player.getVideoData());a?(a=F3(a,uRa(this)),I3(this,a,!1)):vRa(this)}};
g.k.unload=function(){I3(this,null);this.B&&(this.B.abort(),this.B=null);g.GM.prototype.unload.call(this)};
g.k.kf=function(a,b){return H3(this)?"loadCustomEndscreenRenderer"===a?(a=F3(b,"new"),I3(this,a),!0):null:null};
g.k.getOptions=function(){return H3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.xb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<CSa.length;f++){var h=Math.abs(b.width-CSa[f]);if(-1===e||d>=h)e=f,d=h}d=DSa[e];this.u&&g.Gm(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Um(e.element,Math.round(h.width*a.width),f);g.Nm(e.element,m,n);g.Rr(e.element,ESa);m=h.left+h.width/2;h=h.top+l/2;g.L(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Rr(e.element,DSa);g.L(e.element,d);(e=g.Pg(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.Gm(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())P3(this,this.endscreen.impressionUrls),(a=g.Zx())&&this.endscreen.visualElement&&g.ly(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.D[a];g.L(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.L(b,"ytp-ce-shown");P3(this,c.impressionUrls);(b=g.Zx())&&g.ly(b,c.visualElement,void 0);this.player.V().B&&this.player.Oa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.Qr(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Qr(b,"ytp-ce-shown");this.player.V().B&&this.player.Oa("endscreenelementhidden",a)}};
g.k.KW=function(a){var b=this;a.target===window&&(new g.I(function(){for(var c=g.q(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.Rr(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var CSa=[346,426,470,506,570,640,853,1280,1920],DSa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),ESa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var FRa={U1:"current",c8:"new"};var HRa={CLOSE:"close",v8:"openUrl",SUBSCRIBE:"subscribe"},IRa={XZ:"click",CLOSE:"close",z3:"hidden",V9:"rollOut",W9:"rollOver",N$:"shown"};var ySa={XY:"anchored",aP:"branding",CHANNEL:"channel",T1:"cta",C3:"highlightText",Q4:"label",PLAYLIST:"playlist",p9:"popup",W$:"speech",SUBSCRIBE:"subscribe",raa:"title",VIDEO:"video",Vba:"website"},xSa={aP:"branding",KZ:"card",n2:"drawer",B3:"highlight",s6:"marker",z9:"promotion",TEXT:"text",yca:"widget"};g.w(Y3,g.E);g.k=Y3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.Xy(a,b,{id:c,namespace:"annotations_module"});d&&this.Sa.set(a,d);e&&this.Va.set(a,e);this.context.J.Dd([a])};
g.k.kx=function(){this.context.u.subscribe("resize",this.wy,this)};
g.k.kC=function(a,b,c,d,e,f){if(this.bb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.fh(this.element)};
g.k.wy=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=R3(a);if(f){var h=RRa(f,a.target),l=function(){a.i&&e.context.J.pauseVideo();var m=e.context.videoData.D||!1,n=g.Ht(f||"");m&&n&&(n.v||n.list)?e.context.J.Tj(n.v,b,n.list,!1):g.zL(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);n4(this.context.logger,c,l,d);QRa(f)||(c=g.Zx(),d=b.itct,c&&d&&g.qy(c,g.Vx(d)))}};
g.k.ya=function(){this.Sa.clear();this.Va.clear();g.E.prototype.ya.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.H(this,a);return a.element};g.w(c4,Y3);g.k=c4.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.Vm(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.wy=function(){var a=this.isAvailable();g.$m(this.element,a);g.M(this.context.J.getRootNode(),g.eT.IV_DRAWER_ENABLED,a);u3(this.J)};
g.k.destroy=function(){this.J.Et(!1);try{this.J.getRootNode().removeChild(this.C)}catch(a){}g.xv(this.Z);g.$u(this.xa);this.La&&this.La.dispose();this.D&&this.D.dispose();Y3.prototype.destroy.call(this)};
g.k.BR=function(){if(this.B){n4(this.context.logger,h4(this).tracking.close);var a=g.Zx();a&&this.K&&g.qy(a,this.K);b4(this)}};
g.k.NR=function(){g.M(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.fT=function(){var a=g.Zx(),b=h4(this);b=b?b.De:this.De;a&&b&&g.oy(a,[b])};
g.k.eT=function(){var a=g.Zx(),b=h4(this);b=b?b.De:this.De;a&&b&&g.py(a,[b])};
g.k.kQ=function(){var a=h4(this);n4(this.context.logger,a.tracking.lO);var b=g.Zx();b&&a&&g.oy(b,[a.Wi,a.De])};
g.k.gT=function(){var a=g.Zx(),b=h4(this);a&&b&&g.py(a,[b.Wi])};
g.k.jQ=function(a){var b=h4(this),c=g.Zx();this.i?a?(a=this.context.logger,n4(a,b.tracking.mB),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Wi&&g.qy(c,b.Wi)):(a=this.context.logger,n4(a,b.tracking.mB),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.De&&g.qy(c,b.De)):(a=this.context.logger,n4(a,b.tracking.mB),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.De&&g.qy(c,this.De))};g.w(i4,Y3);i4.prototype.kx=function(){Y3.prototype.kx.call(this);eSa(this)};
i4.prototype.show=function(){Y3.prototype.show.call(this);var a=g.Zx(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.oy(a,[g.Vx(b.itct)])};
i4.prototype.hide=function(){Y3.prototype.hide.call(this);var a=g.Zx(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.py(a,[g.Vx(b.itct)])};g.w(j4,i4);
j4.prototype.show=function(){if(!this.isActive){i4.prototype.show.call(this);if(!this.K){g.L(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Ha:["branding-img","iv-click-target"],W:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.$m(this.u,!1);var b=this.createElement({G:"div",Ha:["branding-img-container"]});b.appendChild(this.u);this.element.appendChild(b);(b=MRa(this.annotation))&&Z3(this,this.u,b,this.annotation.id,
a.session_data);iSa(this,a);this.K=!0}g.$m(this.element,!0);this.isActive=!0;this.u&&fSa(this,this.u)}};
j4.prototype.hide=function(){this.isActive&&(i4.prototype.hide.call(this),g.$m(this.element,!1),this.isActive=!1)};
j4.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);i4.prototype.destroy.call(this)};g.w(k4,i4);g.k=k4.prototype;g.k.show=function(){this.isActive||(i4.prototype.show.call(this),this.X||(kSa(this),this.X=!0),g.$m(this.element,!0),g.Yh(function(){g.Qr(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,m4(this),lSa(this),mSa(this,this.I))};
g.k.hide=function(){this.isActive&&(g.L(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.kC=function(a,b,c,d,e,f){return this.isCollapsed?!1:i4.prototype.kC.call(this,a,b,c,d,e,f)};
g.k.uS=function(a){this.S=!0;l4(this,500,a)};
g.k.tS=function(){this.S=!1;nSa(this)};
g.k.oS=function(a){a.stopPropagation();this.hide()};
g.k.pS=function(a){a.stopPropagation();m4(this);this.isCollapsed=!0;g.L(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();i4.prototype.destroy.call(this)};g.w(o4,g.GM);g.k=o4.prototype;g.k.kf=function(a,b){if(!BSa(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.P1(b))&&p4(this,a),!0;case "removeCustomAnnotationById":return b&&this.i&&(WRa(this.i,b),u3(this.player)),!0}return null};
g.k.getOptions=function(){return BSa(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Jq=function(){var a=this.player.V(),b=this.player.getVideoData();return b.D&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.xL||a.S.get(b.videoId)||g.jG(b)||g.kG(b)?!0:!1};
g.k.pA=function(){if(this.B){var a=this.player.eb().getVideoContentRect(!0);g.Um(this.B.element,a.width,a.height);g.Nm(this.B.element,a.left,a.top)}if(this.i){var b=this.player.sj();a=this.i;b=b.width;g.M(a.C,"iv-drawer-small",426>=b);g.M(a.C,"iv-drawer-big",1280<=b)}};
g.k.lQ=function(a){qSa(this,a.state);g.T(a.state,2)&&(this.Eh()&&this.wk()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Et(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.D=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Pt(h)&&h.responseXML?h.responseXML:null)&&(p4(b,h),g.L(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.GM.prototype.load.call(this);qSa(this,this.player.zb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Cu()&&(a=tSa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.D=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().S.get(d);f&&uSa(e,f);f=f&&(f.Cy||f.Uu);if(!c.Fl||f)c.Va?rSa(this,c.Va,e):(this.jl=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.jl));
g.tM(this.player,this.B.element,4);this.pA();(f=g.jG(c))&&zSa(this,f);(f=g.kG(c))&&f.featuredChannel&&ASa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Va&&(this.jl&&(this.player.removeEventListener("videodatachange",this.jl),this.jl=null),rSa(this,b.Va,a))};
g.k.unload=function(){this.player.Ye("annotations_module");for(var a=g.q(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.K=null;this.i&&(this.i.destroy(),this.i=null,u3(this.player));this.S=!1;this.D&&(this.D.abort(),this.D=null);this.I={};this.u.hide();g.GM.prototype.unload.call(this);this.B.detach();this.jl&&(this.player.removeEventListener("videodatachange",this.jl),this.jl=null)};
g.k.eN=function(a){a===this.player.getVideoData().videoId&&(this.loaded?vSa(this):this.load())};
g.k.Eh=function(){return!!this.i&&this.i.isAvailable()};
g.k.wk=function(){this.Eh();return!!this.i&&this.i.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Eh();this.i&&(a?c?a4(this.i,c,b):a4(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):b4(this.i))};
g.k.Et=function(a,b){this.player.ea(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ya=function(){this.player.V().S.unsubscribe("vast_info_card_add",this.eN,this);g.Qr(this.player.getRootNode(),g.eT.IV_DRAWER_OPEN);for(var a=this.X,b=0,c=a.length;b<c;b++)g.mv.ji(a[b]);this.X.length=0;g.GM.prototype.ya.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.H(this,a);return a.element};g.FM("annotations_module",o4);g.FM("creatorendscreen",G3);})(_yt_player);
