(function(g){var window=this;'use strict';var u4=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},v4=function(a){return g.LE(a)&&a.N("web_player_i_see_captions_3")},FSa=function(a,b){var c,d,e;
return g.A(function(f){if(1==f.i)return c=a+"|"+b,g.x(f,g.Pw(),2);if(3!=f.i){d=f.u;if(!d)throw g.nw("gct");return g.x(f,g.mF(d),3)}e=f.u;return f.return(e.get("captions",c))})},GSa=function(a,b){var c=new g.pF;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.i=a.i;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},HSa=function(a,b,c){FSa(a,b).then(function(d){d&&c(d.trackData,new g.pF(d.metadata))})},w4=function(){this.segments=[]},ISa=function(a,b){var c=g.nc(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.Zb(a.segments,c),g.Zb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.ic(a.segments,c,0,b),g.ic(a.segments,c+1,0,b)))},x4=function(a,b,c,d,e,f){g.E.call(this);
this.policy=a;this.player=b;this.Z=c;this.S=d;this.D=e;this.X=f;this.Y=this.player.V();this.C=new w4;this.I=-1;this.B=this.u=this.i=null;this.K=new g.I(this.ML,1E3,this);this.events=new g.LC(this);g.H(this,this.K);g.H(this,this.events);this.events.T(b,"SEEK_COMPLETE",this.rA);this.rA();this.ML()},JSa=function(a){return a.i&&a.i.D?a.i.D+a.player.cd()<a.player.getCurrentTime():!1},KSa=function(a,b){var c=g.FB(g.aC(b,a.policy,{})),d={format:"RAW",
withCredentials:!0};a.D&&(d.responseType="arraybuffer");a.B=g.Ph(g.ou(c,d,3,100).then(function(e){a:{e=e.xhr;a.isDisposed();if(a.u){var f=!(a.D?e.response:e.responseText)||400<=e.status,h=g.Foa(e);if(h){e=g.aC(a.u,a.policy,{});a.u.uj(e,h);KSa(a,a.u);break a}f||(h=a.u.i[0].Ma,null!=a.S&&a.I!==h&&(f=a.u.i[0],a.D?a.S(e.response,1E3*(f.startTime+a.player.cd())):a.S(e.responseText,1E3*(f.startTime+a.player.cd())),a.I=h))}a.u=null;a.B=null}}),function(){a.u=null;
a.B=null;a.ma()});
a.u=b;ISa(a.C,a.u.i[0].Ma)},y4=function(a,b){g.JM.call(this,b.V());
this.i=a;this.J=b;this.B=null;this.D=!1;this.I=g.NE(this.J.V())&&!this.i.isManifestless},MSa=function(a,b){var c=[],d;
for(d in a.i.i)if(a.i.i.hasOwnProperty(d)){var e=a.i.i[d];if(g.LM(e,b||null)){var f=e.info.id,h=f,l="."+f,m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;else{e=f;var n=g.KQa.get(e);null==n&&(n=LSa[e]||LSa[e.replace(/-/g,"_")],g.KQa.set(e,n));h=n||h}c.push(new g.pF({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},NSa=function(a,b){return null!=b&&b in a.i.i?a.i.i[b]:null},OSa=function(a,b,c){var d=
[],e;
for(e in a.i.i)if(a.i.i.hasOwnProperty(e)){var f=a.i.i[e];if(g.LM(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},z4=function(a){if(!PSa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(QSa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},A4=function(a,b,c,d,e,f){var h={};
Object.assign(h,b);Object.assign(h,a.params);Object.assign(h,c);var l={};Object.assign(l,b.pd);a.params.pd&&Object.assign(l,a.params.pd);Object.assign(l,c.pd);h.pd=l;g.W.call(this,{G:"div",L:"caption-window",W:{id:"caption-window-"+a.id,dir:1===h.Jf?"rtl":"ltr",tabindex:"0",lang:h.lang},U:[{G:"span",L:"captions-text",W:{style:"word-wrap: normal; display: block;"}}]});this.D=[];this.xa=!1;this.u=a;this.Ba=this.Aa=null;this.playerWidth=e;this.playerHeight=f;this.I=null;this.maxWidth=.96*e;this.Va=.96*
f;this.i=h;this.wb=c;this.Ja=b;this.C=this.Fa("captions-text");this.rb=""!==this.C.style.getPropertyValue("box-decoration-break")||""!==this.C.style.getPropertyValue("-webkit-box-decoration-break");this.Ka=d/360*16;this.type=0;this.Wa=this.Ka*RSa(l);a=new g.Mx(this.element,!0);g.H(this,a);a.subscribe("dragstart",this.oQ,this);a.subscribe("dragmove",this.nQ,this);a.subscribe("dragend",this.mQ,this);this.bb=this.Za=0;b="";this.i.windowOpacity&&(a=z4(this.i.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+
","+this.i.windowOpacity+")");a={"background-color":b,display:!1===this.i.isVisible?"none":"","text-align":SSa[this.i.textAlign]};this.rb&&(a["border-radius"]=b?this.Wa/8+"px":"");if(this.B=2===this.u.params.Jf||3===this.u.params.Jf)b=this.element,c="vertical-rl",1===this.i.PG&&(c="vertical-lr"),g.Jc&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.Gm(b,"-o-writing-mode",c),g.Gm(b,"-webkit-writing-mode",c),g.Gm(b,"writing-mode",c),g.Gm(b,"text-orientation","upright"),g.L(b,"ytp-vertical-caption"),3===this.u.params.Jf&&
(g.Gm(b,"text-orientation",""),g.Gm(b,"transform","rotate(180deg)"));g.Gm(this.element,a);switch(this.i.gi){case 0:case 1:case 2:g.L(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.L(this.element,"ytp-caption-window-bottom")}},RSa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},TSa=function(a,b){var c={},d=b.background?b.background:a.i.pd.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.i.pd.backgroundOpacity;d=z4(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.rb&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Wa/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Ka*RSa(b)+"px";d=1;e=b.color||a.i.pd.color;if(b.color||null!=b.textOpacity)e=z4(e),d=null==b.textOpacity?a.i.pd.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.lD&&(h=e=b.lD);var l=a.Ka/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Gu()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.i.pd.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.xj&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.OS&&(c.visibility="hidden");1===b.cL&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.RE||g.Gj,3===a.u.params.Jf?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Oj||2===b.Oj||3===b.Oj||4===b.Oj||5===b.Oj)if(g.RE)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Oj){case 4:case 3:c["text-emphasis-position"]="under left";
c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},USa=function(a){a.I=g.bh("SPAN");
g.Gm(a.I,{display:"block"});g.L(a.I,"caption-visual-line");a.C.appendChild(a.I)},VSa=function(a,b){var c=g.bh("SPAN");
g.Gm(c,{display:"inline-block","white-space":"pre-wrap"});g.Gm(c,TSa(a,b));c.classList.add("ytp-caption-segment");a.I.appendChild(c);c.previousElementSibling&&(g.Gm(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Gm(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},WSa=function(a,b,c){a.xa=a.xa||!!c;
var d={};Object.assign(d,a.i.pd);Object.assign(d,c||b.i);Object.assign(d,a.wb.pd);(c=!a.I)&&USa(a);for(var e=a.Aa&&a.Ba&&g.Ve(d,a.Ba)?a.Aa:VSa(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(USa(a),e=VSa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.ch(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.RE||!g.Jm(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.Jm(n.children[2],"text-emphasis-position")&&(m=
a.B?"padding-left":"padding-bottom"),g.Xg?g.Gm(e,m,"1em"):g.Gm(e,m,"0.5em")))}a.Ba=d;a.Aa=e;a.D.push(b)},B4=function(a,b,c,d){g.JM.call(this,a);
this.videoData=b;this.audioTrack=c;this.Ta=d;this.C=b.zD},C4=function(a,b,c,d,e,f,h){A4.call(this,a,b,c,d,e,f,h);
this.type=1},D4=function(a,b,c,d,e,f,h){A4.call(this,a,b,c,d,e,f,h);
this.type=2;this.K=[];this.X=this.S=this.La=0;this.Z=NaN;this.jb=0;this.vb=null;this.Sa=new g.I(this.MV,433,this);g.L(this.element,"ytp-caption-window-rollup");g.H(this,this.Sa);g.Gm(this.element,"overflow","hidden")},XSa=function(a,b){if(!b)return"";
a.B&&1!==a.u.params.PG&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},YSa=function(a){a.K=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.Cm,c=0,d=0,e=a.K.length-1;c<b&&-1<e;){var f=a.K[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.K.length<b&&(d*=b/a.K.length);a.S=d;b=Math;c=b.max;isNaN(a.Z)&&((d=a.i.hn)?(e=g.bh("SPAN"),g.ih(e,"\u2013".repeat(d)),g.Gm(e,TSa(a,a.i.pd)),a.C.appendChild(e),a.Z=e.offsetWidth,a.C.removeChild(e)):a.Z=0);d=a.C;a.X=c.call(b,a.Z,a.jb,(a.B?d.offsetHeight:d.offsetWidth)+1)},ZSa=function(a,b){YSa(a);
var c=a.K.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.S-c;if(c!==a.La){var d=0<c&&0===a.La;b||isNaN(c)||d||(g.L(a.element,"ytp-rollup-mode"),g.Hr(a.Sa));g.Gm(a.C,"transform",XSa(a,c));a.La=c}YSa(a)},E4=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.Xy.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.i=h},F4=function(a,b,c,d,e){g.Xy.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.i=[]},$Sa=function(a){var b="_"+G4++;
return new F4(0,0x8000000000000,0,b,a)},bTa=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Zd){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=aTa(l.textContent,n.textContent,p.textContent,f.textContent,h);return new E4(a,b,e,c,l,d,m)}switch(m.Zd){case 9:case 10:m.Oj=1;break;case 11:m.Oj=2;break;case 12:m.Oj=3;break;case 13:m.Oj=4;break;case 14:m.Oj=5}return new E4(a,b,e,c,l.textContent||"",d,m)},aTa=function(a,b,c,d,e){var f=g.Gu(),h=
f?g.bh("DIV"):g.bh("RUBY"),l=g.bh("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.bh("DIV"):g.bh("RP");a.textContent=b;h.appendChild(a);b=f?g.bh("DIV"):g.bh("RT");b.textContent=c;h.appendChild(b);c=e.Zd;if(10===c||11===c||12===c||13===c||14===c)if(g.Gm(b,"text-emphasis-style","filled circle"),g.Gm(b,"text-emphasis-color","currentcolor"),g.Gm(b,"webkit-text-emphasis","filled circle"),11===e.Zd||13===e.Zd)g.Gm(b,"webkit-text-emphasis-position","under left"),g.Gm(b,"text-emphasis-position","under left");c=!0;if(4===e.Zd||7===e.Zd||12===e.Zd||
14===e.Zd)g.Gm(h,"ruby-position","over"),g.Gm(h,"-webkit-ruby-position","before");else if(5===e.Zd||6===e.Zd||11===e.Zd||13===e.Zd)g.Gm(h,"ruby-position","under"),g.Gm(h,"-webkit-ruby-position","after"),c=!1;e=f?g.bh("DIV"):g.bh("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.Gm(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.Gm(f,"display","none"),f=f.nextElementSibling,g.Gm(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Gm(h.lastElementChild,"display","none"),d?(g.Gm(h,"padding-top","0.6em"),g.Gm(f,"top","0")):(g.Gm(h,"padding-bottom","0.6em"),g.Gm(f,"bottom","0")));return h},H4=function(){g.E.apply(this,arguments)},I4=function(a){H4.call(this);
this.C=a;this.pens={};this.S={};this.X={};this.D="_"+G4++;this.K={};this.B=this.i=null;this.I=!0},J4=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},K4=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},L4=function(a,b){a=J4(a,b);
return void 0!==a?a:null},N4=function(a,b){a=a.getAttribute(b);
if(null!=a)return M4.test(a),a},cTa=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.X[d]:a.C);a=L4(b,"mh");null!=a&&(c.Ys=a);a=L4(b,"ju");null!=a&&(c.textAlign=a);a=L4(b,"pd");null!=a&&(c.Jf=a);a=L4(b,"sd");null!=a&&(c.PG=a);a=N4(b,"wfc");null!=a&&(c.windowColor=a);b=J4(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},dTa=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.S[d]);a=L4(b,"ap");null!=a&&(c.gi=a);a=J4(b,"cc");null!=a&&(c.hn=a);a=J4(b,"ah");null!=a&&(c.hh=a);a=J4(b,"rc");null!=a&&(c.Cm=a);b=J4(b,"av");null!=b&&(c.Pj=b);return c},eTa=function(a,b,c,d){var e={};
Object.assign(e,dTa(a,b));Object.assign(e,cTa(a,b));d?g.Ve(e,a.C)?(d=a.D,e=a.C):d="_"+G4++:d=b.getAttribute("id")||"_"+G4++;a=J4(b,"t")+c;b=J4(b,"d")||0x8000000000000;if(2===e.Jf||3===e.Jf)c=e.Cm,e.Cm=e.hn,e.hn=c;return new F4(a,b,0,d,e)},O4=function(a){H4.call(this);
this.I=a;this.i=new Map;this.C=new Map;this.D=new Map;this.B=new Map},P4=function(a){a=g.rg(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},fTa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.Cm=a);b=b.ccColCount;void 0!==b&&(f.hn=b);if(2===f.Jf||3===f.Jf)b=f.Cm,f.Cm=f.hn,f.hn=b;return new F4(c,d,0,e,f)},R4=function(){this.B=this.time=this.mode=this.u=0;
this.C=new Q4(this);this.D=new Q4(this);this.i=[];this.clear()},hTa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{np:a,
Zm:b,result:0};a=gTa[a];b=gTa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Zm===d;if(d)return{np:a,Zm:b,result:1}}else if(b&128&&1<=a&&31>=a)return{np:a,Zm:b,result:2};return{np:a,Zm:b,result:3}},jTa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.B&&a.reset(),a.C.u.clear(),a.D.u.clear()):(a.B=0,iTa(a.C,b,c,d))},kTa=function(a,b){a.i.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.q(a.i),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?jTa(a,d.DJ,d.EJ,b):1===d.type&&a.u&496&&iTa(a.D,d.DJ,d.EJ,b);a.i.length=0},S4=function(){this.type=0},T4=function(){this.state=this.Zm=this.np=0},lTa=function(){this.timestamp=this.i=0},U4=function(a){this.D=a;
this.B=[];this.i=this.u=this.row=0;this.style=new S4;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new lTa}},V4=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.B[m][p];
if(0!==r.i){0===c&&(c=m,d=p);n=String.fromCharCode(r.i);var t=r.timestamp;t<e&&(e=t);r.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===r.i||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.B[h][m],r=p.i,0!==r&&(0===c&&(c=h,d=m),n=String.fromCharCode(r),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===r)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},qTa=function(a,b){switch(a){case 0:return mTa[(b&127)-32];
case 1:return nTa[b&15];case 2:return oTa[b&31];case 3:return pTa[b&31]}return 0},W4=function(a){return a.B[a.row][a.u]},X4=function(a,b,c){2<=b&&1<a.u&&(--a.u,W4(a).i=0);
var d=W4(a);d.timestamp=a.D.time+0;d.i=qTa(b,c);32>a.u&&a.u++},rTa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.i=l.i;h.timestamp=l.timestamp}},Y4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},Z4=function(a){a.row=0<a.i?a.i:1;
a.u=1;Y4(a,0,15)},$4=function(a){this.B=a;
this.D=0;this.style=new S4;this.I=new U4(this.B);this.K=new U4(this.B);this.text=new U4(this.B);this.u=this.I;this.C=this.K;this.i=this.u},a5=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.i||(V4(d,c),Z4(a.u),Z4(a.C),d.row=15,d.i=b,e=!0)}a.style.set(3);a.i=d;a.i.style=a.style;a.B.mode=1<<d.C;e?d.u=1:d.i!==b&&(d.i>b?(V4(d,c),Y4(d,d.row-d.i,b)):d.row<b&&(b=d.i),d.i=b)},sTa=function(a){a.style.set(1);
a.i=a.C;a.i.i=0;a.i.style=a.style;a.B.mode=1<<a.i.C},tTa=function(a){a.style.set(4);
a.i=a.text;a.i.style=a.style;a.B.mode=1<<a.i.C},Q4=function(a){this.i=a;
this.D=0;this.B=new $4(this.i);this.I=new $4(this.i);this.u=new T4;this.C=this.B},iTa=function(a,b,c,d){a.u.update();
b=hTa(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.np;c=b.Zm;if(32<=e||!e)a.i.mode&a.i.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.i,b&96&&X4(a,0,b),c&96&&X4(a,0,c),0!==b&&0!==c&&3===a.style.type&&V4(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.np=e,b.Zm=c,b.state=2,b=e&8?a.I:a.B,a.C=b,a.i.mode=1<<(a.D<<2)+(b.D<<1)+(4===b.style.type?1:0),(a.i.mode|1<<(a.D<<2)+(b.D<<1)+(4!==b.style.type?1:0))&a.i.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.i;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.i&&(d=c.i,d===c.row))break;var f=1+c.row-c.i,h=1+d-c.i;rTa(c,h,f,c.i);b=f;e=c.i;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));Y4(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:X4(b.i,0,32);break a;case 48:57===c?(d=b.i,W4(d).i=0,32>d.u&&d.u++):X4(b.i,1,c&15)}break;case 2:c&32&&X4(b.i,2,c&31);break;case 3:c&32&&X4(b.i,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:sTa(b);
break;case 33:d=b.i;1<d.u&&(--d.u,W4(d).i=0);break;case 36:d=b.i;b=W4(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:a5(b,2,d);break;case 38:a5(b,3,d);break;case 39:a5(b,4,d);break;case 40:X4(b.i,0,32);break;case 41:b.style.set(2);b.i=b.u;b.i.i=0;b.i.style=b.style;b.B.mode=1<<b.i.C;break;case 42:d=b.text;d.i=15;d.style.set(4);Z4(d);tTa(b);break;case 43:tTa(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:V4(a,d)}Y4(a,
0,15);break;case 45:b:{a=b.i;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.i&&(a.i=2,a.row<a.i&&(a.row=a.i));b=a.row-a.i+1;V4(a,d);rTa(a,b,b+1,a.i-1);Y4(a,a.row,1)}break;case 46:Y4(b.C,0,15);break;case 47:V4(b.u,d),b.C.updateTime(b.B.time+0),d=b.C,b.C=b.u,b.u=d,sTa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.i,32<(d.u+=c&3)&&(d.u=32)}}},uTa=function(){},b5=function(a,b,c){this.trackData=a;
this.K=c;this.version=this.I=this.C=this.i=0;this.u=new DataView(this.trackData);this.B=[]},c5=function(a){var b=a.i;
a.i+=1;return a.u.getUint8(b)},d5=function(a){var b=a.i;
a.i+=4;return a.u.getUint32(b)},e5=function(a,b){H4.call(this);
this.B=a;this.C=b;this.track="CC3"===this.C.languageName?4:0;this.i=new R4;this.i.u=1<<this.track},f5=function(a){if("string"===typeof a)return!1;
a=new b5(a,8,0);return vTa(a)},vTa=function(a){if(!(a.i<a.u.byteLength)||1380139777!==d5(a))return!1;
a.version=c5(a);if(1<a.version)return!1;c5(a);c5(a);c5(a);return!0},g5=function(){H4.call(this)},wTa=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.xj=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new E4(b,c,d,e.id,p.nodeValue,f||0<n,g.Se(l)?void 0:l),m.push(p),e.i.push(p);else{var r={};Object.assign(r,l);wTa(a,b,c,d,e,!0,p,r,m)}}},h5=function(a){var b=a.split(":");
a=0;b=g.q(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},xTa=function(a,b,c,d){d=Object.assign({Ys:0},d);
return new F4(a,b,c,"_"+G4++,d)},i5=function(a,b){g.E.call(this);
this.J=a;this.Y=b;this.i=null;this.u=this.J.Es()},DTa=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.Y.N("enable_h5_ssdai_caption")&&b){var f=e,h=yTa(a,b,d),l=[];try{for(var m=g.q(h),n=m.next();!n.done;n=m.next()){var p=n.value,r=p.trackData,t=p.GG;l="string"!==typeof r?l.concat(zTa(a,c,r,t,f)):"WEBVTT"===r.substring(0,6)?l.concat(ATa(a,r,t)):l.concat(BTa(a,c,r,t))}var u=l}catch(v){g.fy(v),a.clear(),u=[]}if(0!==u.length)return u}a.Y.N("html5_disable_rawcc_killswitch")?"string"!==typeof b&&(u=new DataView(b),8<=u.byteLength&&1718909296===u.getUint32(4)&&(u=g.fB(u,0,1835295092),b=a.Y.N("html5_fix_mdat_offset_killswitch")?
b.slice(u.dataOffset,u.dataOffset+u.size):b.slice(u.dataOffset,u.offset+u.size),f5(b)||(b=g.fb(new Uint8Array(b))))):b=CTa(a,b);if(!b)return[];try{return"string"!==typeof b?zTa(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?ATa(a,b,d):BTa(a,c,b,d)}catch(v){return g.fy(v),a.clear(),[]}},CTa=function(a,b){if("string"===typeof b||f5(b))return b;
var c=new DataView(b);if(8>=c.byteLength||1718909296!==c.getUint32(4))return"";c=g.fB(c,0,1835295092);if(!c||!c.size)return"";a=a.Y.N("html5_fix_mdat_offset_killswitch")?b.slice(c.dataOffset,c.dataOffset+c.size):b.slice(c.dataOffset,c.offset+c.size);return g.fb(new Uint8Array(a))},yTa=function(a,b,c){if("string"===typeof b||f5(b))return[{trackData:b,
GG:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.yna(d);if(a.u&&e){var f=g.rna(e);e=e.i;f&&e&&a.u.Fx(e,f)}f=g.oB(d,1835295092);if(!f||!f.length||!f[0].size)return[];a=[];f=g.q(f.entries());for(e=f.next();!e.done;e=f.next()){var h=g.q(e.value);e=h.next().value;h=h.next().value;h=g.fb(new Uint8Array(b.slice(h.dataOffset,h.offset+h.size)));a.push({trackData:h,GG:c+1E3*e})}ETa(d,a,c);return a=a.filter(function(l){return!!l.trackData})},ETa=function(a,b,c){var d=
g.fB(a,0,1836476516),e=9E4;
d&&(e=g.gB(d)||9E4);d=0;var f=g.oB(a,1836019558);f=g.q(f.entries());for(var h=f.next();!h.done;h=f.next()){var l=g.q(h.value);h=l.next().value;l=l.next().value;h<b.length&&(l=g.fB(a,l.dataOffset,1953653094))&&(l=g.fB(a,l.dataOffset,1952867444))&&(l=g.mB(l)/e*1E3,0===h&&(d=l),b[h].GG=l-d+c||c*h*1E3)}},zTa=function(a,b,c,d,e){if(!f5(c))throw Error("Invalid binary caption track data");
a.i||(a.i=new e5(e,b));return a.i.u(c,d)},ATa=function(a,b,c){a.i||(a.i=new g5);
a=a.i.u(b,c);.01>Math.random()&&g.gy(Error("Deprecated subtitles format in web player: WebVTT"));return a},BTa=function(a,b,c,d){if("{"===c[0])try{return a.i||(a.i=new O4(FTa(b))),a.i.u(c,d)}catch(f){return g.fy(f),[]}var e=g.P1(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.i||(a.i=new I4(FTa(b),a.Y)),a.i.u(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},FTa=function(a){var b=
{};
if(a=g.sF(a))b.lang=a,g.jPa.test(a)&&(b.Jf=1);return b},l5=function(a){g.GM.call(this,a);
var b=this;this.J=a;this.Y=this.J.V();this.videoData=this.J.getVideoData();this.kb=this.J.eb();this.C={pd:{}};this.D={pd:{}};this.xa=[];this.S={};this.Ka={};this.Z=!1;this.vb=g.sG(this.videoData);this.Wa=g.Gxa(this.videoData,this.J);this.rb=!!this.videoData.captionTracks.length;this.wb=!!this.videoData.ac;this.La="3"===this.Y.controlsType;this.u=this.I=this.K=this.Ja=this.Za=null;this.Sa=new i5(this.J,this.Y);this.i=null;this.oa=new g.LC(this);this.Va=new g.W({G:"div",L:"ytp-caption-window-container",
W:{id:"ytp-caption-window-container"}});var c=null,d=g.ys("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.ls(d));this.storage=c;c=a.kd();this.bb=!(null===c||void 0===c||!c.yx());this.B=GTa(this);this.X=!this.B&&this.La&&this.bb&&this.Wa;g.H(this,this.Sa);this.B?this.Ba=this.Aa=null:(this.Aa=new g.Dr(this.hH,void 0,this),g.H(this,this.Aa),this.Ba=new g.I(this.bX,2E3,this),g.H(this,this.Ba));g.H(this,this.oa);this.Y.N("caption_window_container_killswitch")||g.tM(this.player,this.Va.element,
4);g.H(this,this.Va);this.B||this.oa.T(a,"resize",this.jH);(this.jb=!g.Cx()&&!this.J.isFullscreen()&&!this.B&&!this.X&&!this.Y.N("switch_captions_to_track_tag_when_fullscreen_api_unavailable_killswitch"))&&this.oa.T(a,"resize",this.TU);this.oa.T(a,"onPlaybackAudioChange",this.dU);this.oa.T(a,g.Zy("captions"),function(e){b.onCueRangeEnter(e)});
this.oa.T(a,g.$y("captions"),function(e){b.onCueRangeExit(e)});
j5(this,k5(this,"display-settings")||{})},ITa=function(a){if(1===a.Y.Sa||1===a.videoData.Ju||"alwayson"===g.bG(a.videoData,"yt:cc"))return!0;
if(2===a.Y.Sa){var b;g.PE(a.Y)?b=HTa(a):b=k5(a,"module-enabled");if(null!=b)return!!b}if(a.videoData.captionTracks.length)var c=a.player.getAudioTrack().u;b=u4(a.player.getAudioTrack(),v4(a.Y));var d=g.bG(a.videoData,"yt:cc");if(void 0===m5(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===b)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===b)return"on"===d}else return"on"===d;return"ON"===c||"on"===g.bG(a.videoData,"yt:cc")},n5=function(a,b){if(a.i&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.i||"FORCED_ON"===a.u},m5=function(a){var b=void 0,c=g.Rv(g.Qv.getInstance(),65);
if(g.PE(a.Y)&&null!=c){if(null!=HTa(a))return!1;b=!c}return b},JTa=function(a){var b;
a.vb?b=new B4(a.Y,a.videoData,a.player.getAudioTrack(),a.player):a.Wa?b=new y4(a.videoData.i,a.player):a.rb?b=new g.KM(a.Y,a.videoData,a.player.getAudioTrack()):b=new g.MM(a.Y,a.videoData.ac,a.videoData.videoId,g.nsa(a.videoData),a.videoData.gj);return b},p5=function(a,b){if(a.u){if(a.I&&a.I.C)return a.I.C;
b||(b=a.wb?!1:a.rb?!1:!0);b=g.HM(a.u.u,b);for(var c=[a.videoData.captionsLanguagePreference,a.Y.captionsLanguagePreference,g.bG(a.videoData,"yt:cc_default_lang")],d=0;d<c.length;d++)for(var e=0;e<b.length;e++)if(g.sF(b[e])===c[d])return b[e];return a.I&&a.I.B?a.I.B:(c=b.find(function(f){return f.isDefault}))?c:b[0]||o5(a)}return null},o5=function(a){return a.I&&a.I.i},q5=function(a){var b=o5(a);
return!!b&&a.i===b},KTa=function(a){var b=u4(a.player.getAudioTrack(),v4(a.Y)),c;
"CAPTIONS_INITIAL_STATE_UNKNOWN"===b?m5(a)||a.Z||ITa(a)?c=p5(a,a.Z):n5(a)&&(c=o5(a)):"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=p5(a,a.Z):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&n5(a)&&(c=o5(a));if(a.B||a.X){var d=g.HM(a.u.u,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.bh("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.qF(f));h.setAttribute("srclang",g.sF(f));h.setAttribute("id",f.toString());a.X||h.setAttribute("src",a.u.Rp(f,"vtt"));f===c&&h.setAttribute("default",
"1");b.push(h)}c=a.J.kd();c.Nu(b);c=c.xe();a.bb&&a.oa.T(c.textTracks,"change",a.uW)}else!a.i&&c&&r5(a,c),a.player.Oa("onCaptionsTrackListChanged"),a.player.Oa("onApiChange")},LTa=function(a,b){var c=a.J.kd().xe().textTracks;
a=a.i.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},r5=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.Z=c,a.Z&&(g.PE(a.Y)?s5(a,!!b):t5(a,"module-enabled",!!b)));a.i=b;n5(a)&&(a.i=o5(a));a.load()},MTa=function(a,b){a.Y.N("caption_window_container_killswitch")?g.tM(a.player,b,4):a.Va.element.appendChild(b)},NTa=function(a,b){var c=a.kb.getVideoContentRect(!0).height;
if(!c)return null;var d=a.i?g.sF(a.i):null;d&&g.jPa.test(d)&&(b.params.Jf=1);d=a.kb.getPlayerSize();switch(null!=b.params.Ys?b.params.Ys:1<b.i.length?1:0){case 1:return new C4(b,a.C,a.D,c,d.width,d.height,a.Y.experiments);case 2:return new D4(b,a.C,a.D,c,d.width,d.height,a.Y.experiments);default:return new A4(b,a.C,a.D,c,d.width,d.height,a.Y.experiments)}},j5=function(a,b,c){c=void 0===c?!1:c;
var d=u5.pd;a.C={};Object.assign(a.C,u5);a.C.pd={};Object.assign(a.C.pd,d);a.D={pd:{}};var e=b.backgroundOverride?a.D:a.C,f=b.background||d.background;M4.test(f);e.pd.background=f;e=b.colorOverride?a.D:a.C;f=b.color||d.color;M4.test(f);e.pd.color=f;e=b.windowColorOverride?a.D:a.C;f=b.windowColor||u5.windowColor;M4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.C;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.pd.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.D:a.C;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.pd.fontSizeIncrement=f;f=b.fontStyleOverride?a.D:a.C;e=b.fontStyle;null==e&&(e=d.bold&&d.xj?3:d.bold?1:d.xj?2:0);f=f.pd;switch(e){case 1:f.bold=!0;delete f.xj;break;case 2:delete f.bold;f.xj=!0;break;case 3:f.bold=!0;f.xj=!0;break;default:delete f.bold,delete f.xj}e=b.textOpacityOverride?a.D:a.C;f=b.textOpacity;null==f&&(f=d.textOpacity);e.pd.textOpacity=f;e=b.windowOpacityOverride?a.D:a.C;f=b.windowOpacity;null==f&&(f=u5.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.D:a.C;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.pd.charEdgeStyle=f;e=b.fontFamilyOverride?a.D:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.pd.fontFamily=f;a.loaded&&a.jH();c&&t5(a,"display-settings",b)},v5=function(a,b,c){b&&!a.K?(b=$Sa({Jf:0,
lang:"en"}),a.K=[b,new E4(b.start,b.end-b.start,0,b.id,null!==c&&void 0!==c?c:"Captions look like this")],a.player.Dd(a.K)):!b&&a.K&&(OTa(a,a.K),a.K=null)},OTa=function(a,b){a.player.Gf(b);
g.sc(b,function(c){g.$b(this.xa,c)},a);
g.Er(a.Aa)},k5=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},t5=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}},s5=function(a,b){a.J.isInline()||g.uy("yt-player-sticky-caption",b,2592E3)},HTa=function(a){if(!a.J.isInline())return g.vy("yt-player-sticky-caption")},GTa=function(a){var b=a.J.kd();
b=!(null===b||void 0===b||!b.xx());return a.La&&b&&!a.Wa};
g.wS.prototype.Dv=g.ca(33,function(a){var b=2;this.Aa.has(a)?b=0:g.rDa(this,a)&&(b=1);return b});
g.aV.prototype.Dv=g.ca(32,function(a){return this.od.Dv(a)});
g.wS.prototype.Fx=g.ca(31,function(a,b){this.Ka.set(a,b)});
g.aV.prototype.Fx=g.ca(30,function(a,b){this.od.Fx(a,b)});
g.YM.prototype.Vr=g.ca(29,function(){this.ma();for(var a=g.Pg(document,"track",void 0,this.i),b=0;b<a.length;b++)g.fh(a[b])});
g.dS.prototype.Vr=g.ca(28,function(){this.ra.Vr()});
g.YM.prototype.yx=g.ca(27,function(){return!(!this.i.textTracks||!this.i.textTracks.addEventListener)});
g.dS.prototype.yx=g.ca(26,function(){return this.ra.yx()});
g.YM.prototype.xx=g.ca(25,function(){return!!this.i.textTracks});
g.dS.prototype.xx=g.ca(24,function(){return this.ra.xx()});
g.YM.prototype.Nu=g.ca(23,function(a){this.ma();for(var b=0;b<a.length;b++)this.i.appendChild(a[b])});
g.dS.prototype.Nu=g.ca(22,function(a){this.ra.Nu(a)});
g.JM.prototype.XF=g.ca(21,function(){return!1});
g.JM.prototype.Wn=g.ca(20,function(){});
g.KM.prototype.Wn=g.ca(19,function(a,b,c){var d=this;this.isDisposed();b=this.Rp(a,b);this.Mm();this.i=g.lu(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})});
g.MM.prototype.Wn=g.ca(18,function(a,b,c){var d=this;this.isDisposed();b=this.Rp(a,b);this.Mm();this.i=g.lu(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})});
g.LU.prototype.Pv=g.ca(6,function(){return this.K});
g.RX.prototype.Pv=g.ca(5,function(){var a;return(null===(a=g.vM(this))||void 0===a?void 0:a.Es())||null});
g.mM.prototype.Es=g.ca(4,function(){return this.app.Pv()});
g.sX.prototype.Es=g.ca(3,function(){var a;return(null===(a=this.Ya)||void 0===a?void 0:a.Pv())||null});
var LSa={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",ale:"Aleut",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",arp:"Arapaho",ars:"Najdi Arabic",arw:"Arawak",as:"Assamese",asa:"Asu",ast:"Asturian",av:"Avaric",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",
az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bas:"Basaa",bax:"Bamun",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bez:"Bena",bfd:"Bafut",bg:"Bulgarian",bh:"Bhojpuri",bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bkm:"Kom",bla:"Siksika",bm:"Bambara",bn:"Bangla",bo:"Tibetan",br:"Breton",bra:"Braj",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",
cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cr:"Cree",crh:"Crimean Turkish",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",
de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",
es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fulah",ff_Adlm:"Fulah (Adlam)",ff_Latn:"Fulah (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",
gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",
iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kha:"Khasi",
kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Lahnda",lam:"Lamba",lb:"Luxembourgish",
lez:"Lezghian",lg:"Ganda",li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",
mi:"M\u0101ori",mic:"Mi'kmaq",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",
ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",
pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",
sad:"Sandawe",sah:"Sakha",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",
sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",swc:"Congo Swahili",
syc:"Classical Syriac",syr:"Syriac",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",
uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",
za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};w4.prototype.contains=function(a){a=g.nc(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
w4.prototype.length=function(){return this.segments.length/2};
g.w(x4,g.E);g.k=x4.prototype;g.k.ya=function(){g.E.prototype.ya.call(this);this.B&&this.B.cancel()};
g.k.rA=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.cd();var b=this.i;this.i=g.Rb(this.Z.Zl(a).i);b!==this.i&&this.X&&this.X()};
g.k.reset=function(){this.C=new w4;this.I=-1;this.B&&(this.B.cancel(),this.B=null)};
g.k.ML=function(){var a;this.isDisposed();var b;if(b=null!=this.i)b=this.i,b=b.i.Qm(b);if(b&&!this.B&&!(this.i&&30<this.i.startTime-this.player.getCurrentTime())){b=this.i;b=b.i.wu(b);if(this.Y.N("enable_h5_ssdai_caption")&&(null===(a=this.player.getVideoData())||void 0===a?0:a.enableServerStitchedDai)){var c=this.player.Es();if(c){var d=b.i[0].Ma,e=c.Kp(b.i[0].C,d,b.i[0].i.info.id,3);if(e)if(c=c.Dv(d),0===c)e&&(b.B=new g.HA(e));else if(2===c){this.K.start();JSa(this)&&this.seekTo(this.player.getCurrentTime());
return}}}b.i[0].duration?(this.C.contains(b.i[0].Ma)||KSa(this,b),this.i=g.Rb(b.i)):!this.Y.N("force_caption_seek_for_live_killswitch")&&JSa(this)&&this.seekTo(this.player.getCurrentTime())}this.K.start()};
g.k.ma=function(){};
g.w(y4,g.JM);g.k=y4.prototype;g.k.Wn=function(a,b,c){var d=this;this.Mm();b=NSa(this,a.getId());b||(b=a.languageCode,b=this.i.isManifestless?OSa(this,b,"386"):OSa(this,b));if(b){var e=1E3*(b.index.getStartTimeInPeriod(b.index.getFirstSegmentNumber())-b.index.getStartTime(b.index.getFirstSegmentNumber())),f=new g.Exa(this.Y);this.B=new x4(f,this.J,b,function(h,l){c(h,a,l,e)},this.I||g.uC(b.info),function(){d.B&&d.B.reset();
d.D=!0})}};
g.k.XF=function(){var a=this.D;this.D=!1;return a};
g.k.Us=function(a){var b=this.I?[new g.pF({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.pF({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.i.isManifestless?MSa(this,"386"):MSa(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())g.IM(this.u,c.value);a()};
g.k.Mm=function(){this.B&&(this.B.dispose(),this.B=null)};
g.k.Rp=function(){return""};
var M4=/^#(?:[0-9a-f]{3}){1,2}$/i,QSa=/#(.)(.)(.)/,PSa=/^#(?:[0-9a-f]{3}){1,2}$/i;var SSa=["left","right","center","justify"];g.w(A4,g.W);g.k=A4.prototype;g.k.oQ=function(a,b){var c=g.Tm(this.element,this.element.parentElement);this.Za=a-c.x;this.bb=b-c.y;g.L(this.element,"ytp-dragging")};
g.k.nQ=function(a,b){var c=g.Vm(this.element);a=a-this.Za-.02*this.playerWidth;var d=b-this.bb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.rg(e,0,2));var f=(d+c.height/2)/this.Va*3;f=Math.floor(g.rg(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.rg(a,0,1);c=(d+f/2*c.height)/this.Va;c=100*g.rg(c,0,1);this.u.params.gi=b;this.u.params.Pj=c;this.u.params.hh=a;this.i.gi=b;this.i.Pj=c;this.i.hh=a;this.Ja.gi=b;this.Ja.Pj=c;this.Ja.hh=a;this.LN()};
g.k.mQ=function(){g.Qr(this.element,"ytp-dragging")};
g.k.LN=function(){this.It(this.D)};
g.k.getType=function(){return this.type};
g.k.It=function(a){var b=Math.min(this.AK(),this.maxWidth),c=this.zK(),d="";3===this.u.params.Jf&&(d="rotate(180deg)");g.Gm(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.WC(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.i.hh+2;d=this.i.gi;switch(d){case 0:case 3:case 6:(b=this.i.pd.fontSizeIncrement)&&0<b&&2!==this.i.Jf&&3!==
this.i.Jf&&(e=Math.max(e/(1+2*b),2));a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.C.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.i.Pj+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.Gm(this.element,
a)};
g.k.WC=function(a){var b;for(b=0;b<a.length&&a[b]===this.D[b];b++);if(this.xa||this.D.length>b)b=0,this.xa=!1,this.D=[],this.I=this.Ba=this.Aa=null,g.dh(this.C);for(;b<a.length;b++)WSa(this,a[b])};
g.k.AK=function(){return 0};
g.k.zK=function(){return 0};
g.k.toString=function(){return g.W.prototype.toString.call(this)};g.w(B4,g.JM);B4.prototype.Wn=function(a,b,c){HSa(this.videoData.videoId,a.vssId,c)};
B4.prototype.Us=function(a){if(this.audioTrack)for(var b=g.q(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.IM(this.u,c.value);a()};g.w(C4,A4);C4.prototype.WC=function(a){var b=this.u.i;A4.prototype.WC.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.i===e)var d=f;else{d={};Object.assign(d,c.i);Object.assign(d,PTa);var e=c.i;var f=d}WSa(this,c,d)}};
var PTa={OS:!0};g.w(D4,A4);g.k=D4.prototype;g.k.LN=function(){g.Ir(this.Sa)};
g.k.MV=function(){g.Qr(this.element,"ytp-rollup-mode");this.It(this.vb,!0)};
g.k.zK=function(){return this.B?this.X:this.S};
g.k.AK=function(){return this.B?this.S:this.X};
g.k.It=function(a,b){this.vb=a;if(this.u.params.Cm){for(var c=0,d=0;d<this.D.length&&c<a.length;d++)this.D[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.D.concat(a.slice(c)));this.jb=this.X;this.S=this.X=0;A4.prototype.It.call(this,a);ZSa(this,b)}A4.prototype.It.call(this,a)};g.w(E4,g.Xy);E4.prototype.toString=function(){return g.Xy.prototype.toString.call(this)};g.w(F4,g.Xy);F4.prototype.toString=function(){return g.Xy.prototype.toString.call(this)};
var G4=0;g.w(H4,g.E);H4.prototype.u=function(){return[]};
H4.prototype.reset=function(){};g.w(I4,H4);I4.prototype.reset=function(){this.K={};this.B=this.i=null;this.I=!0};
I4.prototype.u=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.q(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.q(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=K4(a,"b");
null!=l&&(h.bold=l);l=K4(a,"i");null!=l&&(h.xj=l);l=K4(a,"u");null!=l&&(h.underline=l);l=L4(a,"et");null!=l&&(h.charEdgeStyle=l);l=L4(a,"of");null!=l&&(h.offset=l);l=N4(a,"bc");null!=l&&(h.background=l);l=N4(a,"ec");null!=l&&(h.lD=l);l=N4(a,"fc");null!=l&&(h.color=l);l=L4(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=J4(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=J4(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=J4(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=L4(a,"rb");null!=l&&10!==l&&0!==
l&&(h.Zd=10<l?l-1:l);a=L4(a,"hg");null!=a&&(h.cL=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.X[c]=cTa(this,a);break;case "wp":c=a.getAttribute("id"),this.S[c]=dTa(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.q(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.i=eTa(this,a,b,!1);(a=this.K[this.i.id])&&a.end>this.i.start&&(a.end=this.i.start);this.K[this.i.id]=this.i;d.push(this.i);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.D;h=
!!K4(a,"a");l=(J4(a,"t")||0)+l;var m=J4(a,"d")||5E3;h||(!this.I&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&"\n"===this.B.text&&(this.B.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.pens[p]:null;var r=Array.from(a.childNodes);r.length&&(this.I=null!=a.getAttribute("d"));for(var t=0;t<r.length;t++){var u=r[t],v=void 0;0<t&&(h=!0);var y=void 0;1===u.nodeType&&(y=u);if(y&&"s"===y.tagName){if((u=(u=y.getAttribute("p"))?this.pens[u]:null)&&u.Zd&&(1===u.Zd?(u=r.slice(t,t+4),
4===u.length&&(v=bTa(l,m,f,h,n,u,this.pens),t+=3)):v=bTa(l,m,f,h,n,[y],this.pens)),!v){var z=y;v=l;y=m;u=f;var D=h,F=n,G=z.textContent?z.textContent:"",J=z.getAttribute("p");J=J?this.pens[J]:null;z=J4(z,"t")||0;v=new E4(v+z,y-z,F,u,G,D,J)}}else v=new E4(l,m,n,f,u.textContent||"",h,p);c.push(v);this.B=v}if(0<c.length)for(c[0].windowId===this.D&&(this.i=eTa(this,a,b,!0),d.push(this.i)),a=g.q(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.i.id,this.i.i.push(c),d.push(c)}b=d}else b=[];return b};var QTa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.w(O4,H4);O4.prototype.reset=function(){this.B.clear()};
O4.prototype.u=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.q(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.i.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.xj=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.lD=P4(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=P4(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=P4(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.Zd=10<h?h-1:h,f.Oj=QTa.get(f.Zd));e.hgHorizGroup&&(f.cL=e.hgHorizGroup);this.i.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.q(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.I),void 0!==e.mhModeHint&&(f.Ys=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.Jf=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.PG=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=P4(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.q(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),void 0!==e.ahHorPos&&
(f.hh=e.ahHorPos),void 0!==e.apPoint&&(f.gi=e.apPoint),void 0!==e.avVerPos&&(f.Pj=e.avVerPos),void 0!==e.ccCols&&(f.hn=e.ccCols),void 0!==e.rcRows&&(f.Cm=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.q(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=fTa(this,l,d,e,f),a.push(d),this.B.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+G4++,h=fTa(this,l,d,e,f),a.push(h),this.B.set(f,h));0===e&&(e=5E3);h=this.B.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,r=null;l.pPenId&&(r=this.i.get(l.pPenId));for(l=0;l<p.length;l++){var t=p[l],u=t.utf8;if(u){var v=t.tOffsetMs||0,y=null;t.pPenId&&(y=this.i.get(t.pPenId));if(2===(null!=h.params.Ys?h.params.Ys:1<h.i.length?1:0)&&m&&"\n"===u)continue;if(t=y&&1===y.Zd)if(t=l,t+3>=p.length||!p[t+1].pPenId||!p[t+2].pPenId||!p[t+3].pPenId)t=!1;else{var z=p[t+1].pPenId;(z=this.i.get(z))&&z.Zd&&2===z.Zd?(z=p[t+2].pPenId,z=this.i.get(z),!z||!z.Zd||3>z.Zd?t=!1:(z=p[t+3].pPenId,t=(z=this.i.get(z))&&
z.Zd&&2===z.Zd?!0:!1)):t=!1}if(t){v=p[l+1].utf8;t=p[l+3].utf8;z=p[l+2].utf8;var D=this.i.get(p[l+2].pPenId);u=aTa(u,v,z,t,D);m=new E4(d,e,n,f,u,m,y);l+=3}else m=new E4(d+v,e-v,n,h.id,u,m,y||r);m&&(a.push(m),h.i.push(m))}m=!0}}}b=a}else b=[];return b};R4.prototype.clear=function(){this.B=this.time=this.mode=0;this.i=[];this.reset()};
R4.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var gTa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];S4.prototype.set=function(a){this.type=a};
S4.prototype.get=function(){return this.type};
T4.prototype.clear=function(){this.state=0};
T4.prototype.update=function(){this.state=2===this.state?1:0};
T4.prototype.isValid=function(){return 0!==this.state};
T4.prototype.matches=function(a,b){return this.isValid()&&a===this.np&&b===this.Zm};
lTa.prototype.reset=function(){this.timestamp=this.i=0};
U4.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
U4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.i?a+"_":a+String.fromCharCode(d.i)}a+="\n"}return a};
U4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.i=0;this.u=this.row=1};
var mTa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],nTa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],oTa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],pTa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];$4.prototype.reset=function(a,b){this.D=b;this.style.set(2);this.u=this.I;this.C=this.K;this.i=this.u;var c=(a<<2)+(b<<1);this.I.reset(c);this.K.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
Q4.prototype.reset=function(a){this.D=a;this.u.clear();this.C=this.B;this.B.reset(a,0);this.I.reset(a,1)};uTa.prototype.D=function(){};g.w(b5,uTa);b5.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+G4++;c=c/1E3-this.K;d=d/1E3-this.K;a=new F4(c,d-c,5,f,{textAlign:0,gi:0,hh:2.5*b,Pj:5.33*a});e=new E4(c,d-c,5,f,e);this.B.push(a);this.B.push(e)}};
g.w(e5,H4);e5.prototype.u=function(a){a=new b5(a,a.byteLength,this.B);if(vTa(a)){for(;a.i<a.u.byteLength;)for(0===a.version?a.C=d5(a)*(1E3/45):1===a.version&&(a.C=4294967296*d5(a)+d5(a)),a.I=c5(a);0<a.I;a.I--){var b=c5(a),c=c5(a),d=c5(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.i,b.i.push({time:a.C,type:this.track,DJ:c,EJ:d,order:b.i.length}))}kTa(this.i,a);return a.B}return[]};
e5.prototype.reset=function(){this.i.clear()};g.w(g5,H4);
g5.prototype.u=function(a,b){var c=[];a=a.split(RTa);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!STa.test(e)){var h=w5.exec(e);if(h&&4<=h.length){var l=h5(h[1]),m=h5(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var r="";var t=null,u="";n=g.q(n);for(var v=n.next();!v.done;v=n.next())if(v=v.value.split(":"),2===v.length){var y=v[1];switch(v[0]){case "line":v=y.split(",");v[0].endsWith("%")&&(p=v[0],h.Pj=Number.parseInt(p,10),2===v.length&&(r=v[1].trim()));break;case "position":v=
y.split(",");t=v[0];h.hh=Number.parseInt(t,10);2===v.length&&(u=v[1].trim());break;case "align":switch(y){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||r||(r="end");if(!t)switch(h.textAlign){case 0:h.hh=0;break;case 1:h.hh=100;break;case 2:h.hh=50}if(null!=h.textAlign){p=0;switch(r){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(u){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}r=0>p||8<p?7:p;h.gi=r}e=e.substring(w5.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");u=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=xTa(l,m,5,u),m=new E4(l,m,5,f.id,h,!1,g.Se(e)?void 0:e),c.push(f),c.push(m),f.i.push(m);else for(r=h.split(TTa),1===r.length?(h=5,u=xTa(l,m,h,u)):(p=h=6,u=Object.assign({hn:32},u),u=new F4(l,m,p,"_"+G4++,u)),c.push(u),p=l,t=0;t<r.length;t++)n=r[t],0===t%2?(v=g.P1("<html>"+n+"</html>"),v.getElementsByTagName("parsererror").length?
(y=v.createElement("span"),y.appendChild(v.createTextNode(n))):y=v.firstChild,wTa(this,p,m-(p-l),h,u,0<t,y,e,c)):p=h5(n)+f}w5.lastIndex=0}}return c};
var STa=/^NOTE/,RTa=/(?:\r\n|\r|\n){2,}/,w5=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),TTa=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.kS.Jz(g5,{u:"wvppt"});g.w(i5,g.E);i5.prototype.clear=function(){this.i&&this.i.dispose();this.i=null};
i5.prototype.reset=function(){this.i&&this.i.reset()};
i5.prototype.ya=function(){g.E.prototype.ya.call(this);this.clear()};var u5={windowColor:"#080808",windowOpacity:0,textAlign:2,gi:7,hh:50,Pj:100,pd:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.w(l5,g.GM);g.k=l5.prototype;g.k.ya=function(){if(this.B||this.X){var a=this.J.kd();a&&!a.isDisposed()&&a.Vr()}else v5(this,!1);g.GM.prototype.ya.call(this)};
g.k.Jq=function(){if(this.La)return this.B||this.X;var a=u4(this.player.getAudioTrack(),v4(this.Y));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?n5(this):m5(this)||n5(this)?!0:ITa(this)};
g.k.load=function(){var a=this;g.GM.prototype.load.call(this);var b=!this.Y.N("web_player_captions_track_list_changed_killswitch");this.I=this.player.getAudioTrack();this.u?(this.i&&(this.Sa.clear(),this.B?LTa(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.Wn(this.i,"json3",function(c,d,e,f){c&&(a.u.XF()&&(a.xa=[],a.J.Ye("captions"),g.Er(a.Aa),a.Sa.reset()),c=DTa(a.Sa,c,d,e,f),a.Y.N("tv_caption_performance_optimization")?a.player.Dd(c,void 0,a.Wa):a.player.Dd(c),!a.Z||a.X||q5(a)||g.BE(a.Y)||
g.uE(a.Y)||(g.Jr(a.Ba),c=$Sa({gi:0,hh:5,Pj:5,Cm:2,textAlign:0,Jf:0,lang:"en"}),a.Ja=[c],d=["Click "," for settings"],a.Za||(e=new g.nK(g.DK()),g.H(a,e),a.Za=e.element),e=c.end-c.start,(f=g.qF(a.i))&&a.Ja.push(new E4(c.start,e,0,c.id,f)),a.Ja.push(new E4(c.start,e,0,c.id,d[0]),new E4(c.start,e,0,c.id,a.Za,!0),new E4(c.start,e,0,c.id,d[1],!0)),a.player.Dd(a.Ja),g.Hr(a.Ba)),!a.Z||a.X||q5(a)||(g.PE(a.Y)?s5(a,!0):t5(a,"module-enabled",!0),a.I&&(a.I.C=a.i),a.player.Rq()),a.Z=!1)}),!b||this.B||this.X||q5(this)||
this.player.Oa("captionschanged",g.rF(this.i))),b||(this.i&&!q5(this)?this.player.Oa("captionschanged",g.rF(this.i)):this.player.Oa("onCaptionsTrackListChanged"))):(this.u=JTa(this),g.H(this,this.u),this.u.Us(function(){KTa(a)}))};
g.k.unload=function(){this.B&&this.i?LTa(this,!1):(this.Ba&&g.Jr(this.Ba),this.player.Ye("captions"),this.xa=[],this.u&&this.u.Mm(),this.Sa.clear(),this.K&&this.player.Dd(this.K),this.jH());g.GM.prototype.unload.call(this);this.player.Rq();this.player.Oa("captionschanged",{})};
g.k.create=function(){this.Jq()&&this.load()};
g.k.uW=function(){for(var a=this.J.kd().xe().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;var d=g.HM(this.u.u,!0);for(var e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.i:null)!==b&&r5(this,b,!0)};
g.k.WX=function(){!this.i&&this.B||this.unload()};
g.k.onCueRangeEnter=function(a){this.xa.push(a);g.Er(this.Aa)};
g.k.onCueRangeExit=function(a){g.$b(this.xa,a);this.u instanceof y4&&this.u.I&&this.player.Gf([a]);g.Er(this.Aa)};
g.k.VW=function(a){if(a instanceof F4){var b=this.S[a.id];b&&b.u!==a&&(b.dispose(),delete this.S[a.id],b=null);b||(b=NTa(this,a))&&(this.S[a.id]=b)}else b=a.windowId,this.Ka[b]||(this.Ka[b]=[]),this.Ka[b].push(a)};
g.k.getCaptionWindowContainerId=function(){return this.Va.element.id};
g.k.bX=function(){OTa(this,this.Ja);this.Ja=null};
g.k.hH=function(){var a=this;if(!this.jb||!this.B){this.Aa.stop();g.Te(this.Ka);this.xa.sort(g.Yy);var b=this.xa;if(this.K){var c=g.Bp(b,function(d){return-1===this.K.indexOf(d)},this);
c.length&&(b=c)}g.sc(b,this.VW,this);g.De(this.S,function(d,e){a.Ka[e]?(d.element.parentNode||(d instanceof D4||d instanceof C4||g.Ge(a.S,function(f,h){h!==e&&f.u.params.gi===d.u.params.gi&&f.u.params.hh===d.u.params.hh&&f.u.params.Pj===d.u.params.Pj&&(f.dispose(),delete a.S[h]);return h===e},a),MTa(a,d.element)),d.It(a.Ka[e])):(d.dispose(),delete a.S[e])},this)}};
g.k.gX=function(){j5(this,{},!0);this.Y.N("web_player_disable_publish_captions_settings_changed_on_reset")||this.player.Oa("captionssettingschanged")};
g.k.lS=function(){var a=u5.pd;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.xj?3:a.bold?1:a.xj?2:0,textOpacity:a.textOpacity,windowColor:u5.windowColor,windowOpacity:u5.windowOpacity};var b=k5(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.LO=function(a,b){var c={};Object.assign(c,k5(this,"display-settings"));Object.assign(c,a);j5(this,c,b);this.player.Oa("captionssettingschanged")};
g.k.jH=function(){!this.B&&this.loaded&&(g.De(this.S,function(a,b){a.dispose();delete this.S[b]},this),this.hH())};
g.k.kf=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.rg(b,-2,4);this.LO({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&r5(this,this.i,!0);break;case "stickyLoading":void 0!==b&&this.Y.B&&(g.PE(this.Y)?s5(this,!!b):t5(this,"module-enabled",!!b));break;case "track":if(!this.u)return{};if(b){if(this.B)break;if(!g.Oa(b))break;if(g.Se(b)){r5(this,null,!0);break}a=g.HM(this.u.u,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&e.languageName!==
b.languageName||(c=b.translationLanguage?GSa(e,b.translationLanguage):e)}!c||c===this.i&&this.loaded||(b=g.qpa(),a=g.sF(c),b.length&&a===b[b.length-1]||(b.push(a),g.uy("yt-player-caption-language-preferences",b)),r5(this,c,!0))}else return this.loaded&&this.i&&!q5(this)?g.rF(this.i):{};return"";case "tracklist":return this.u?g.nn(g.HM(this.u.u,!(!b||!b.includeAsr)),function(f){return g.rF(f)}):[];
case "translationLanguages":return this.u?this.u.C.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.B||void 0===b||v5(this,!!b);break;case "sampleSubtitlesCustomized":this.B||v5(this,!!b,b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Y.B&&a.push("stickyLoading");return a};
g.k.jE=function(){var a=this.i;if(a){var b=a.vssId;a.translationLanguage&&b&&!this.Y.N("auto_translation_logging_killswitch")&&(b="t"+b+"."+g.sF(a));return{cc:b}}return{}};
g.k.MX=function(){this.loaded&&this.i&&!q5(this)?(g.PE(this.Y)?s5(this,!1):t5(this,"module-enabled",!1),this.unload(),n5(this,!0)&&r5(this,o5(this),!1)):this.tO()};
g.k.tO=function(){this.loaded&&this.i&&!q5(this)||r5(this,q5(this)||!this.i?p5(this,!0):this.i,!0)};
g.k.dU=function(){var a=q5(this);n5(this,a)?r5(this,this.player.getAudioTrack().i,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Jq()&&(a?r5(this,p5(this),!1):this.load()))};
g.k.TU=function(){var a=this.J.kd();a&&!a.isDisposed()&&a.Vr();this.J.isFullscreen()?(this.B=this.La=!0,this.loaded&&KTa(this)):(this.La="3"===this.Y.controlsType,this.B=GTa(this));r5(this,this.i)};
g.kS.Jz(l5,{hH:"smucd"});g.FM("captions",l5);})(_yt_player);
