(function(g){var window=this;'use strict';var ZTa=function(a,b){a.Oa("onAutonavCoundownStarted",b)},K5=function(a,b,c){g.M(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Ke(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.gF&&(b.lengthText?(e=b.lengthText||null,f=b.jq||null):b.lengthSeconds&&(e=g.nL(b.lengthSeconds),f=g.nL(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.cF(d).type;var l=b instanceof g.gF?b.isLivePlayback:null,m=b instanceof g.gF?b.isUpcoming:null;c={title:b.title,author:b.author,author_and_views:b.shortViewCount?b.author+" \u2022 "+b.shortViewCount:b.author,aria_label:b.Hl||g.CH("Watch $TITLE",{TITLE:b.title}),duration:e,
timestamp:f,url:b.Jk(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:b.shortViewCount?b.shortViewCount+" \u2022 "+b.publishedTimeText:b.publishedTimeText,autoplayAlternativeHeader:b.Ym};b instanceof g.fF&&(c.playlist_length=b.playlistLength);a.update(c)},L5=function(a){var b=a.V(),c=b.i;
g.W.call(this,{G:"a",L:"ytp-autonav-suggestion-card",W:{href:"{{url}}",target:c?b.I:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},U:[{G:"div",Ha:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],W:{style:"{{background}}"},U:[{G:"div",W:{"aria-label":"{{timestamp}}"},Ha:["ytp-autonav-timestamp"],va:"{{duration}}"},{G:"div",Ha:["ytp-autonav-live-stamp"],va:"Live"},{G:"div",
Ha:["ytp-autonav-upcoming-stamp"],va:"Upcoming"},{G:"div",L:"ytp-autonav-list-overlay",U:[{G:"div",L:"ytp-autonav-mix-text",va:"Mix"},{G:"div",L:"ytp-autonav-mix-icon"}]}]},{G:"div",Ha:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],va:"{{title}}"},{G:"div",Ha:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],va:"{{author}}"},{G:"div",Ha:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],va:"{{views_and_publish_time}}"}]});this.J=a;this.suggestion=
null;this.i=c;this.Ra("click",this.onClick);this.Ra("keypress",this.onKeyPress)},N5=function(a,b){b=void 0===b?!1:b;
g.W.call(this,{G:"div",L:"ytp-autonav-endscreen-countdown-container"});var c=this;this.I=b;this.D=void 0;this.u=0;b=a.V();var d=b.i;this.J=a;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);this.i=new g.W({G:"div",L:"ytp-autonav-endscreen-upnext-container",W:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},U:[{G:"div",
L:"ytp-autonav-endscreen-upnext-header"},{G:"div",L:"ytp-autonav-endscreen-upnext-alternative-header",va:"{{autoplayAlternativeHeader}}"},{G:"a",L:"ytp-autonav-endscreen-link-container",W:{href:"{{url}}",target:d?b.I:""},U:[{G:"div",L:"ytp-autonav-endscreen-upnext-thumbnail",W:{style:"{{background}}"},U:[{G:"div",W:{"aria-label":"{{timestamp}}"},Ha:["ytp-autonav-timestamp"],va:"{{duration}}"},{G:"div",Ha:["ytp-autonav-live-stamp"],va:"Live"},{G:"div",Ha:["ytp-autonav-upcoming-stamp"],va:"Upcoming"}]},
{G:"div",L:"ytp-autonav-endscreen-video-info",U:[{G:"div",L:"ytp-autonav-endscreen-premium-badge"},{G:"div",L:"ytp-autonav-endscreen-upnext-title",va:"{{title}}"},{G:"div",L:"ytp-autonav-endscreen-upnext-author",va:"{{author}}"},{G:"div",L:"ytp-autonav-view-and-date",va:"{{views_and_publish_time}}"},{G:"div",L:"ytp-autonav-author-and-view",va:"{{author_and_views}}"}]}]}]});g.H(this,this.i);this.i.Ea(this.element);d||this.T(this.i.Fa("ytp-autonav-endscreen-link-container"),"click",this.lI);this.J.Hb(this.element,
this,115127);this.J.Hb(this.i.Fa("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.W({G:"div",L:"ytp-autonav-overlay"});g.H(this,this.overlay);this.overlay.Ea(this.element);this.B=new g.W({G:"div",L:"ytp-autonav-endscreen-button-container"});g.H(this,this.B);this.B.Ea(this.element);this.cancelButton=new g.W({G:"button",Ha:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button"],W:{"aria-label":"Cancel autoplay"},va:"Cancel"});g.H(this,this.cancelButton);
this.cancelButton.Ea(this.B.element);this.cancelButton.Ra("click",this.tQ,this);this.J.Hb(this.cancelButton.element,this,115129);this.playButton=new g.W({G:"a",Ha:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button"],W:{href:"{{url}}",role:"button","aria-label":"Play next video"},va:"Play Now"});g.H(this,this.playButton);this.playButton.Ea(this.B.element);this.playButton.Ra("click",this.lI,this);this.J.Hb(this.playButton.element,this,115130);this.C=new g.I(function(){M5(c)},
500);
g.H(this,this.C);this.kI();this.T(a,"autonavvisibility",this.kI)},Q5=function(a){var b=a.J.sj(!0,a.J.isFullscreen());
g.M(a.element,"ytp-autonav-endscreen-small-mode",a.vf(b));g.M(a.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.iB);g.M(a.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.J.Yd());g.M(a.J.getRootNode(),"countdown-running",a.Jh());g.M(a.element,"ytp-player-content",a.J.Yd());g.Gm(a.overlay.element,{width:b.width+"px"});if(!a.Jh()){a.J.Yd()?O5(a,Math.round(P5(a)/1E3)):O5(a);b=!!a.suggestion&&!!a.suggestion.Ym;var c=a.J.Yd()||!b;g.M(a.element,"ytp-autonav-endscreen-upnext-alternative-header-only",
!c&&b);g.M(a.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.qK(a.B,a.J.Yd())}},M5=function(a){var b=P5(a),c=Math,d=c.min;
var e=a.u?Date.now()-a.u:0;c=d.call(c,e,b);O5(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Jh()?a.select(!0):a.Jh()&&a.C.start()},P5=function(a){var b=a.J.Ip();
return 0<=b?b:g.S(a.J.V().experiments,"autoplay_time")||1E4},O5=function(a,b){b=void 0===b?-1:b;
a=a.i.Fa("ytp-autonav-endscreen-upnext-header");g.dh(a);if(0<=b){b=String(b);var c="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.ch("Up next in $SECONDS".slice(0,d)));var e=g.bh("span");g.Nr(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.ih(e,b);a.appendChild(e);a.appendChild(g.ch("Up next in $SECONDS".slice(d+c.length)));return}}g.ih(a,"Up next")},R5=function(a,b){g.W.call(this,{G:"div",
Ha:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},S5=function(a){g.W.call(this,{G:"div",
Ha:["ytp-upnext","ytp-player-content"],W:{"aria-label":"{{aria_label}}"},U:[{G:"div",L:"ytp-cued-thumbnail-overlay-image",W:{style:"{{background}}"}},{G:"span",L:"ytp-upnext-top",U:[{G:"span",L:"ytp-upnext-header",va:"Up Next"},{G:"span",L:"ytp-upnext-title",va:"{{title}}"},{G:"span",L:"ytp-upnext-author",va:"{{author}}"}]},{G:"a",L:"ytp-upnext-autoplay-icon",W:{role:"button",href:"{{url}}","aria-label":"Play next video"},U:[{G:"svg",W:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
U:[{G:"circle",L:"ytp-svg-autoplay-circle",W:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",L:"ytp-svg-autoplay-ring",W:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",L:"ytp-svg-fill",W:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",L:"ytp-upnext-bottom",U:[{G:"span",L:"ytp-upnext-cancel"},{G:"span",L:"ytp-upnext-paused",
va:"Autoplay is paused"}]}]});this.api=a;this.cancelButton=null;this.D=this.Fa("ytp-svg-autoplay-ring");this.B=this.notification=this.i=this.suggestion=null;this.C=new g.I(this.Fy,5E3,this);this.u=0;var b=this.Fa("ytp-upnext-cancel");this.cancelButton=new g.W({G:"button",Ha:["ytp-upnext-cancel-button","ytp-button"],W:{tabindex:"0","aria-label":"Cancel autoplay"},va:"Cancel"});g.H(this,this.cancelButton);this.cancelButton.Ra("click",this.uQ,this);this.cancelButton.Ea(b);this.cancelButton&&this.api.Hb(this.cancelButton.element,
this,115129);g.H(this,this.C);this.api.Hb(this.element,this,18788);b=this.Fa("ytp-upnext-autoplay-icon");this.T(b,"click",this.vQ);this.api.Hb(b,this,115130);this.mI();this.T(a,"autonavvisibility",this.mI);this.T(a,"mdxnowautoplaying",this.VU);this.T(a,"mdxautoplaycanceled",this.WU);g.M(this.element,"ytp-upnext-mobile",this.api.V().isMobile)},$Ta=function(a,b){return b?b:0<=a.api.Ip()?a.api.Ip():g.S(a.api.V().experiments,"autoplay_time")||1E4},T5=function(a,b){b=$Ta(a,b);
var c=Math,d=c.min;var e=(0,g.P)()-a.u;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.D.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Jh()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Jh()&&a.i.start()},U5=function(a){R5.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.W({G:"div",L:"ytp-suggestion-panel",U:[{G:"div",Ha:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],va:"More videos"}]});this.K=new g.W({G:"div",L:"ytp-suggestions-container"});this.videos=[];this.B=null;this.D=this.I=!1;this.u=new N5(this.player);g.H(this,this.u);this.u.Ea(this.element);a.getVideoData().Gc?this.i=this.u:(this.i=new S5(a),g.tM(this.player,this.i.element,4),g.H(this,this.i));this.overlay=new g.W({G:"div",
L:"ytp-autonav-overlay-cancelled-state"});g.H(this,this.overlay);this.overlay.Ea(this.element);this.C=new g.LC(this);g.H(this,this.C);g.H(this,this.table);this.table.Ea(this.element);this.table.show();g.H(this,this.K);this.K.Ea(this.table.element);this.hide()},V5=function(a){var b=a.Yd();
b!==a.D&&(a.D=b,a.player.ea("autonavvisibility"),a.D?(a.u!==a.i&&a.u.hide(),a.table.hide()):(a.u!==a.i&&a.u.show(),a.table.show()))},W5=function(a){R5.call(this,a,"subscribecard-endscreen");
this.i=new g.W({G:"div",L:"ytp-subscribe-card",U:[{G:"img",L:"ytp-author-image",W:{src:"{{profilePicture}}"}},{G:"div",L:"ytp-subscribe-card-right",U:[{G:"div",L:"ytp-author-name",va:"{{author}}"},{G:"div",L:"html5-subscribe-button-container"}]}]});g.H(this,this.i);this.i.Ea(this.element);var b=a.getVideoData();this.subscribeButton=new g.JN("Subscribe",null,"Unsubscribe",null,!0,!1,b.aj,b.subscribed,"trailer-endscreen",null,null,a);g.H(this,this.subscribeButton);this.subscribeButton.Ea(this.i.Fa("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Qa);this.Qa();this.hide()},X5=function(a){var b=a.V(),c=g.Ej||g.kE?{style:"will-change: opacity"}:void 0,d=b.i,e=["ytp-videowall-still"];
b.isMobile&&e.push("ytp-videowall-show-text");g.W.call(this,{G:"a",Ha:e,W:{href:"{{url}}",target:d?b.I:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},U:[{G:"div",L:"ytp-videowall-still-image",W:{style:"{{background}}"}},{G:"span",L:"ytp-videowall-still-info",U:[{G:"span",L:"ytp-videowall-still-info-bg",U:[{G:"span",L:"ytp-videowall-still-info-content",W:c,U:[{G:"span",L:"ytp-videowall-still-info-title",va:"{{title}}"},{G:"span",
L:"ytp-videowall-still-info-author",va:"{{author_and_views}}"},{G:"span",L:"ytp-videowall-still-info-live",va:"Live"},{G:"span",L:"ytp-videowall-still-info-duration",va:"{{duration}}"}]}]}]},{G:"span",Ha:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],U:[{G:"span",L:"ytp-videowall-still-listlabel-icon"},"Playlist",{G:"span",L:"ytp-videowall-still-listlabel-length",U:[" (",{G:"span",va:"{{playlist_length}}"},")"]}]},{G:"span",Ha:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
U:[{G:"span",L:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{G:"span",L:"ytp-videowall-still-listlabel-length",va:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.i=new g.LC(this);g.H(this,this.i);this.Ra("click",this.onClick);this.Ra("keypress",this.onKeyPress);this.i.T(a,"videodatachange",this.onVideoDataChange);a.Pg(this.element,this);this.onVideoDataChange()},Y5=function(a){R5.call(this,a,"videowall-endscreen");
var b=this;this.J=a;this.B=0;this.stills=[];this.C=this.videoData=null;this.D=this.K=!1;this.S=null;this.u=new g.LC(this);g.H(this,this.u);this.I=new g.I(function(){g.L(b.element,"ytp-show-tiles")},0);
g.H(this,this.I);var c=new g.W({G:"button",Ha:["ytp-button","ytp-endscreen-previous"],W:{"aria-label":"Previous"},U:[g.vK()]});g.H(this,c);c.Ea(this.element);c.Ra("click",this.zQ,this);this.table=new g.nK({G:"div",L:"ytp-endscreen-content"});g.H(this,this.table);this.table.Ea(this.element);c=new g.W({G:"button",Ha:["ytp-button","ytp-endscreen-next"],W:{"aria-label":"Next"},U:[g.wK()]});g.H(this,c);c.Ea(this.element);c.Ra("click",this.yQ,this);a.getVideoData().Gc?this.i=new N5(a,!0):this.i=new S5(a);
g.H(this,this.i);g.tM(this.player,this.i.element,4);this.hide()},Z5=function(a){return g.uM(a.player)&&a.Pu()&&!a.C},$5=function(a){var b=a.Yd();
b!==a.K&&(a.K=b,a.player.ea("autonavvisibility"))},a6=function(a){g.GM.call(this,a);
var b=this;this.endScreen=null;this.i=this.u=this.B=!1;this.listeners=new g.LC(this);g.H(this,this.listeners);this.env=a.V();aUa(a)?(this.B=!0,bUa(this),this.i?this.endScreen=new U5(a):this.endScreen=new Y5(this.player)):this.env.wd?this.endScreen=new W5(this.player):this.endScreen=new R5(this.player);g.H(this,this.endScreen);g.tM(this.player,this.endScreen.element,4);cUa(this);this.listeners.T(a,"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.Zy("endscreen"),function(c){b.onCueRangeEnter(c)});
this.listeners.T(a,g.$y("endscreen"),function(c){b.onCueRangeExit(c)})},bUa=function(a){var b=a.player.getVideoData();
if(!b||a.i===b.rh&&a.u===b.Gc)return!1;a.i=b.rh;a.u=b.Gc;return!0},aUa=function(a){a=a.V();
return a.vb&&!a.wd},cUa=function(a){a.player.Ye("endscreen");
var b=a.player.getVideoData();b=new g.Xy(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.Xy(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.Dd([b,c])};
g.mM.prototype.Ip=g.ca(2,function(){return this.app.Ip()});
g.RX.prototype.Ip=g.ca(1,function(){return this.getVideoData().hN});g.w(L5,g.W);L5.prototype.select=function(){(this.J.Tj(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.uv||void 0)||this.J.N("web_player_endscreen_double_log_fix_killswitch"))&&this.J.Cb(this.element)};
L5.prototype.onClick=function(a){g.cN(a,this.J,this.i,this.suggestion.sessionData||void 0)&&this.select()};
L5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.fv(a)||(this.select(),g.ev(a))}};g.w(N5,g.W);g.k=N5.prototype;g.k.Zx=function(a){this.suggestion!==a&&(this.suggestion=a,K5(this.i,a),this.playButton.Pa("url",this.suggestion.Jk()),Q5(this))};
g.k.Jh=function(){return 0<this.u};
g.k.Jt=function(){this.Jh()||(this.u=Date.now(),M5(this),ZTa(this.J,P5(this)),g.M(this.J.getRootNode(),"countdown-running",this.Jh()))};
g.k.wq=function(){this.Jm();M5(this);var a=this.i.Fa("ytp-autonav-endscreen-upnext-header");a&&g.ih(a,"Up next")};
g.k.Jm=function(){this.Jh()&&(this.C.stop(),this.u=0)};
g.k.select=function(a){this.J.nextVideo(!1,void 0===a?!1:a);this.Jm()};
g.k.lI=function(a){g.cN(a,this.J)&&(a.currentTarget===this.playButton.element?this.J.Cb(this.playButton.element):a.currentTarget===this.i.Fa("ytp-autonav-endscreen-link-container")&&(a=this.i.Fa("ytp-autonav-endscreen-link-container"),this.J.gb(a,!0),this.J.Cb(a)),this.select())};
g.k.tQ=function(){this.J.Cb(this.cancelButton.element);g.oM(this.J,!0);this.D&&this.J.Oa("innertubeCommand",this.D)};
g.k.onVideoDataChange=function(a,b){a=b.gY;this.D=null===a||void 0===a?void 0:a.command};
g.k.kI=function(){var a=this.J.Yd();this.I&&this.yb!==a&&g.qK(this,a);Q5(this);this.J.gb(this.element,a);this.J.gb(this.cancelButton.element,a);this.J.gb(this.i.Fa("ytp-autonav-endscreen-link-container"),a);this.J.gb(this.playButton.element,a)};
g.k.vf=function(a){return 400>a.width||459>a.height};g.w(R5,g.W);g.k=R5.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.Pu=function(){return!1};
g.k.Yd=function(){return!1};
g.k.vL=function(){return!1};g.w(S5,g.W);g.k=S5.prototype;g.k.Fy=function(){this.notification&&(this.C.stop(),this.qc(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.k.Zx=function(a){this.suggestion=a;K5(this,a,"hqdefault.jpg")};
g.k.mI=function(){g.qK(this,this.api.Yd());this.api.gb(this.element,this.api.Yd());this.api.gb(this.Fa("ytp-upnext-autoplay-icon"),this.api.Yd());this.cancelButton&&this.api.gb(this.cancelButton.element,this.api.Yd())};
g.k.eV=function(){window.focus();this.Fy()};
g.k.Jt=function(a){var b=this;this.Jh()||(g.yv("a11y-announce","Up Next "+this.suggestion.title),this.u=(0,g.P)(),this.i=new g.I(function(){T5(b,a)},25),T5(this,a),ZTa(this.api,$Ta(this,a)));
g.Qr(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.W.prototype.hide.call(this)};
g.k.Jh=function(){return!!this.i};
g.k.wq=function(){this.Jm();this.u=(0,g.P)();T5(this);g.L(this.element,"ytp-upnext-autoplay-paused")};
g.k.Jm=function(){this.Jh()&&(this.i.dispose(),this.i=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.V().N("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.Fy(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.Ke()}),this.B=this.T(this.notification,"click",this.eV),this.C.start())}this.Jm();this.api.nextVideo(!1,a)};
g.k.vQ=function(a){!g.hh(this.cancelButton.element,g.av(a))&&g.cN(a,this.api)&&(this.api.Yd()&&this.api.Cb(this.Fa("ytp-upnext-autoplay-icon")),this.select())};
g.k.uQ=function(){this.api.Yd()&&this.cancelButton&&this.api.Cb(this.cancelButton.element);g.oM(this.api,!0)};
g.k.VU=function(a){this.api.getPresentingPlayerType();this.show();this.Jt(a)};
g.k.WU=function(){this.api.getPresentingPlayerType();this.Jm();this.hide()};
g.k.ya=function(){this.Jm();this.Fy();g.W.prototype.ya.call(this)};g.w(U5,R5);g.k=U5.prototype;g.k.create=function(){R5.prototype.create.call(this);this.C.T(this.player,"appresize",this.Gu);this.C.T(this.player,"onVideoAreaChange",this.Gu);this.C.T(this.player,"videodatachange",this.onVideoDataChange);this.C.T(this.player,"autonavchange",this.nI);this.C.T(this.player,"autonavcancel",this.wQ);this.onVideoDataChange()};
g.k.show=function(){R5.prototype.show.call(this);(this.I||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.oM(this.player,!1);g.uM(this.player)&&this.Pu()&&!this.B?(V5(this),2===this.videoData.autonavState?this.player.V().N("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.Jt():3===this.videoData.autonavState&&this.i.wq()):(g.oM(this.player,!0),V5(this));this.Gu()};
g.k.hide=function(){R5.prototype.hide.call(this);this.i.wq();V5(this)};
g.k.Gu=function(){var a=this.player.sj(!0,this.player.isFullscreen());V5(this);Q5(this.u);g.M(this.element,"ytp-autonav-cancelled-small-mode",this.vf(a));g.M(this.element,"ytp-autonav-cancelled-tiny-mode",this.Nz(a));g.M(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.Gm(this.overlay.element,{width:a.width+"px"});if(!this.D){a=g.q(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){var c=g.q(b.value);b=c.next().value;c=c.next().value;g.M(c.element,
"ytp-suggestion-card-with-margin",1===b%2)}}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length){this.i.Zx(a[0]);this.i!==this.u&&this.u.Zx(a[0]);for(var b=0;b<dUa.length;++b){var c=dUa[b];if(a&&a[c]){this.videos[b]=new L5(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,K5(d,c));g.H(this,this.videos[b]);this.videos[b].Ea(this.K.element)}}}this.Gu()}};
g.k.nI=function(a){1===a?(this.I=!1,this.B=this.videoData.clientPlaybackNonce,this.i.Jm(),this.yb&&this.Gu()):(this.I=!0,this.Yd()&&(2===a?this.i.Jt():3===a&&this.i.wq()))};
g.k.wQ=function(a){a?this.nI(1):(this.B=null,this.I=!1)};
g.k.Pu=function(){return 1!==this.videoData.autonavState};
g.k.vf=function(a){return(910>a.width||459>a.height)&&!this.Nz(a)&&!(400>=a.width||360>=a.height)};
g.k.Nz=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.Yd=function(){return this.yb&&g.uM(this.player)&&this.Pu()&&!this.B};
var dUa=[1,3,2,4];g.w(W5,R5);W5.prototype.Qa=function(){var a=this.player.getVideoData();this.i.update({profilePicture:a.Ph,author:a.author});this.subscribeButton.channelId=a.aj;var b=this.subscribeButton;a.subscribed?b.u():b.B()};g.w(X5,g.W);X5.prototype.select=function(){(this.api.Tj(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.uv||void 0)||this.api.N("web_player_endscreen_double_log_fix_killswitch"))&&this.api.Cb(this.element)};
X5.prototype.onClick=function(a){g.cN(a,this.api,this.u,this.suggestion.sessionData||void 0)&&this.select()};
X5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.fv(a)||(this.select(),g.ev(a))}};
X5.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.V();this.u=a.D?!1:b.i};g.w(Y5,R5);g.k=Y5.prototype;g.k.create=function(){R5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.ul();this.u.T(this.player,"appresize",this.ul);this.u.T(this.player,"onVideoAreaChange",this.ul);this.u.T(this.player,"videodatachange",this.onVideoDataChange);this.u.T(this.player,"autonavchange",this.lC);this.u.T(this.player,"autonavcancel",this.xQ);a=this.videoData.autonavState;a!==this.S&&this.lC(a);this.u.T(this.element,"transitionend",this.vW)};
g.k.destroy=function(){g.Ix(this.u);(0,g.se)(this.stills);this.stills=[];R5.prototype.destroy.call(this);g.Qr(this.element,"ytp-show-tiles");this.I.stop();this.S=this.videoData.autonavState};
g.k.Pu=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){R5.prototype.show.call(this);g.Qr(this.element,"ytp-show-tiles");this.player.V().isMobile?g.Ir(this.I):this.I.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.oM(this.player,!1);Z5(this)?($5(this),2===this.videoData.autonavState?this.player.V().N("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.Jt():3===this.videoData.autonavState&&this.i.wq()):(g.oM(this.player,!0),$5(this))};
g.k.hide=function(){R5.prototype.hide.call(this);this.i.wq();$5(this)};
g.k.vW=function(a){g.av(a)===this.element&&this.ul()};
g.k.ul=function(){if(this.videoData&&this.videoData.suggestions&&this.videoData.suggestions.length){g.L(this.element,"ytp-endscreen-paginate");var a=this.J.sj(!0,this.J.isFullscreen()),b=g.jM(this.J);b&&(b=b.Te()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),h=Math.max(a.height/54,2),l=this.videoData.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<h);){var p=b/2,r=e/2,t=b<=f-2&&n>=r*m,u=e<=h-2&&n>=p*m;if((p+
1)/r*d/c>c/(p/(r+1)*d)&&u)n-=p*m,e+=2;else if(t)n-=r*m,b+=2;else if(u)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.Um(a,m,n);g.Gm(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});this.i.Zx(this.videoData.suggestions[0]);this.i instanceof N5&&Q5(this.i);g.M(this.element,"ytp-endscreen-takeover",Z5(this));$5(this);m+=4;n+=4;for(f=
c=0;f<b;f++)for(h=0;h<e;h++)if(p=c,r=0,d&&f>=b-2&&h>=e-2?r=1:0===h%2&&0===f%2&&(2>h&&2>f?0===h&&0===f&&(r=2):r=2),p=g.sg(p+this.B,l),0!==r){t=this.stills[c];t||(t=new X5(this.player),this.stills[c]=t,a.appendChild(t.element));u=Math.floor(n*h/e);var v=Math.floor(m*f/b),y=Math.floor(n*(h+r)/e)-u-4,z=Math.floor(m*(f+r)/b)-v-4;g.Nm(t.element,v,u);g.Um(t.element,z,y);g.Gm(t.element,"transitionDelay",(h+f)/20+"s");g.M(t.element,"ytp-videowall-still-mini",1===r);g.M(t.element,"ytp-videowall-still-large",
2<r);r=t;p=this.videoData.suggestions[p];r.suggestion!==p&&(r.suggestion=p,t=r.api.V(),u=g.Or(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",K5(r,p,u),g.mE(t)&&(t=p.Jk(),t=g.Ui(t,g.aM("emb_rel_end")),r.Pa("url",t)),(p=(p=p.sessionData)&&p.itct)&&r.api.Gm(r.element,p));c++}g.M(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.fh(e.element),(0,g.re)(e);this.stills.length=c}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.videoData=a,this.ul())};
g.k.yQ=function(){this.B+=this.stills.length;this.ul()};
g.k.zQ=function(){this.B-=this.stills.length;this.ul()};
g.k.vL=function(){return this.i.Jh()};
g.k.lC=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,this.i.Jm(),this.yb&&this.ul()):(this.D=!0,this.yb&&Z5(this)&&(2===a?this.i.Jt():3===a&&this.i.wq()))};
g.k.xQ=function(a){if(a){for(a=0;a<this.stills.length;a++)this.J.gb(this.stills[a].element,!0);this.lC(1)}else this.C=null,this.D=!1;this.ul()};
g.k.Yd=function(){return this.yb&&Z5(this)};g.w(a6,g.GM);g.k=a6.prototype;g.k.Jq=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!aUa(this.player)||b;var c=a.Pe||g.xE(a.u),d=this.player.Av();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.Yd=function(){return this.endScreen.Yd()};
g.k.VS=function(){return this.Yd()?this.endScreen.vL():!1};
g.k.ya=function(){this.player.Ye("endscreen");g.GM.prototype.ya.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.bL;if(b&&b.videoId){var c=this.player.tb().Gd.get("heartbeat");a&&a.suggestions&&a.suggestions.length&&b.videoId===a.suggestions[0].videoId&&!a.FI?a=!1:(this.player.Tj(b.videoId,void 0,void 0,!0,!0,b),c&&c.Wz("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0)}else a=!1;a||(g.GM.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.GM.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.Jq()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){cUa(this);this.B&&bUa(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.i?this.endScreen=new U5(this.player):this.endScreen=new Y5(this.player),g.H(this,this.endScreen),g.tM(this.player,this.endScreen.element,4))};g.FM("endscreen",a6);})(_yt_player);
